<script setup lang="ts">
import ProjectedBook from './ProjectedBook.vue';
import { useWisdomI18n } from './i18n';
import type { SampleBook } from './books';
defineProps<{books:SampleBook[];total:number;query:string}>();
defineEmits<{brief:[id:string];enter:[id:string];remove:[id:string];back:[];clear:[]}>();
const {t}=useWisdomI18n();
</script>
<template>
  <section class="personal-grimoires" :aria-label="t.collection">
    <header><div><small>{{t.recentlyOpened}}</small><h1>{{t.collection}} <span>{{total}}</span></h1></div><button @click="$emit('back')">← {{t.backToTree}}</button></header>
    <div v-if="books.length" class="personal-list"><article v-for="book in books" :key="book.id"><ProjectedBook :book="book"/><div class="personal-book-detail"><h2>{{book.title}}</h2><p>{{book.summary||book.title}}</p><div class="personal-progress"><span>{{book.completed||0}} / {{book.count}} · {{t.completed}}</span><progress :aria-label="t.progressLabel+' · '+book.title" :max="book.count||1" :value="book.completed||0"></progress></div><div class="personal-actions"><button class="remove-grimoire" :data-book="book.id" :aria-label="`${t.removeGrimoire}: ${book.title}`" :title="t.removalKeepsPalace" @click="$emit('remove',book.id)"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M5 10h10"/></svg>{{t.removeGrimoire}}</button><button @click="$emit('brief',book.id)">{{t.brief}} ↗</button><button @click="$emit('enter',book.id)">{{t.open}} →</button></div></div></article></div>
    <div v-else class="personal-empty"><span aria-hidden="true">✧</span><h2>{{query.trim()?t.noMatches:t.emptyCollection}}</h2><p>{{query.trim()?t.trySearch:t.emptyCollectionHelp}}</p><button v-if="query.trim()" @click="$emit('clear')">{{t.clearSearch}}</button><button v-else @click="$emit('back')">{{t.discover}} ↗</button></div>
  </section>
</template>
<style scoped>
.personal-grimoires{position:absolute;top:150px;bottom:115px;right:4.5%;left:41%;display:flex;flex-direction:column;min-height:0;color:#dfeef3}.personal-grimoires>header{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:20px 25px;background:#1a3044ed;border:1px solid #afd3e044;border-radius:4px 22px 4px 4px;backdrop-filter:blur(18px);flex-shrink:0}.personal-grimoires header small{font:8px 'Courier New',monospace;letter-spacing:.13em;color:#c7b9dd;text-transform:uppercase}.personal-grimoires h1{font-size:25px;font-weight:400;margin:9px 0 0}.personal-grimoires h1 span{font:12px 'Courier New',monospace;color:#adc9d7;margin-left:13px}.personal-grimoires header button{border:0;background:none;color:#c1e0e8;font-size:10px;line-height:1.6;text-align:right;max-width:150px;padding:8px}.personal-list{overflow:auto;min-height:0;margin-top:12px;display:flex;flex-direction:column;gap:11px;padding-right:3px;scrollbar-width:thin}.personal-list article{display:grid;grid-template-columns:95px 1fr;align-items:center;gap:25px;padding:22px;background:linear-gradient(110deg,#1a3348ec,#2c2f47e6);border:1px solid #afcde132;border-radius:4px 20px 4px 4px;backdrop-filter:blur(15px);flex-shrink:0}.personal-book-detail{min-width:0}.personal-book-detail>small{font:8px 'Courier New',monospace;color:#adaecb}.personal-book-detail h2{font-size:20px;font-weight:400;margin:8px 0 10px}.personal-book-detail>p{font:12px/1.7 'Segoe UI',sans-serif;color:#bfcdd9;margin:0 0 14px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.personal-progress{display:flex;align-items:center;gap:15px;font:9px 'Courier New',monospace;color:#b6d4dd}.personal-progress progress{width:75px;height:3px;accent-color:#b6dee6}.personal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.personal-actions button,.personal-empty button{border:1px solid #bdc2e34f;background:#afcee912;border-radius:4px 12px 4px 4px;color:#d5c8e8;padding:10px 15px;font-size:11px;min-height:38px}.personal-actions button:last-child{color:#b8eff2;border-color:#a3e4e575}.personal-empty{padding:50px 30px;background:#203249e3;border-radius:4px 20px 4px 4px;text-align:center;margin-top:12px}.personal-empty>span{font-size:42px;color:#d3bfe3}.personal-empty h2{font-weight:400;font-size:25px}.personal-empty p{font:13px/1.7 'Segoe UI',sans-serif;color:#bbcddd}
@media(max-width:1000px){.personal-grimoires{left:28%;right:3%}}
@media(max-width:700px){.personal-grimoires{left:14px;right:14px;top:147px;bottom:93px}.personal-grimoires>header{padding:17px;gap:12px}.personal-grimoires h1{font-size:23px}.personal-grimoires header button{font-size:9px;max-width:110px}.personal-list article{padding:16px 14px;grid-template-columns:64px 1fr;gap:15px}.personal-list :deep(.projected-book){transform:scale(.7);margin-left:-15px}.personal-book-detail h2{font-size:18px;line-height:1.25}.personal-book-detail>p{font-size:11px}.personal-book-detail>small{font-size:7px}.personal-progress{flex-direction:column;align-items:flex-start;gap:8px;font-size:8px}.personal-actions{justify-content:flex-start}.personal-actions button{padding:9px 11px;font-size:10px}.personal-empty{padding:30px 20px}}
</style>
<style scoped>
.personal-actions{flex-wrap:wrap}.personal-actions .remove-grimoire{display:flex;align-items:center;gap:5px;margin-right:auto;background:none;border-color:transparent;color:#c4b4cc;padding-inline:5px;min-height:44px}.remove-grimoire svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.2}.personal-actions .remove-grimoire:hover{color:#efd2e5;border-color:#c9a3bf5e}@media(max-width:700px){.personal-actions{gap:6px}.personal-actions .remove-grimoire{font-size:10px;padding:7px 0}.personal-actions button{min-height:44px}}
</style>
