-- Idempotent whole-book ingestion support for Kaicenat.

ALTER TABLE grimoire ADD COLUMN IF NOT EXISTS source_key text;
ALTER TABLE grimoire ADD COLUMN IF NOT EXISTS source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE UNIQUE INDEX IF NOT EXISTS grimoire_source_key_unique
    ON grimoire (source_key) WHERE source_key IS NOT NULL;

ALTER TABLE section ADD COLUMN IF NOT EXISTS source_key text;
ALTER TABLE section ADD COLUMN IF NOT EXISTS source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE UNIQUE INDEX IF NOT EXISTS section_book_source_key_unique
    ON section (grimoire_id, source_key) WHERE source_key IS NOT NULL;

ALTER TABLE knowledge ADD COLUMN IF NOT EXISTS source_key text;
ALTER TABLE knowledge ADD COLUMN IF NOT EXISTS source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE UNIQUE INDEX IF NOT EXISTS knowledge_section_source_key_unique
    ON knowledge (section_id, source_key) WHERE source_key IS NOT NULL;

ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS label text;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS working_summary text;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS ref_id text;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS labelled_references jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS object_reference_labels jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS loose_references_guessed_objects jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS book_image (
    book_image_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    section_id int REFERENCES section(section_id) ON DELETE SET NULL,
    knowledge_id int REFERENCES knowledge(knowledge_id) ON DELETE SET NULL,
    source_image_id text NOT NULL,
    semantic_context_name text,
    storage_key text NOT NULL,
    url text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (grimoire_id, source_image_id)
);

CREATE INDEX IF NOT EXISTS book_image_knowledge_idx ON book_image (knowledge_id);
CREATE INDEX IF NOT EXISTS book_image_section_idx ON book_image (section_id);

ALTER TABLE knowledge ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
ALTER TABLE book_image ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
CREATE INDEX IF NOT EXISTS knowledge_active_source_idx
    ON knowledge (section_id, source_key) WHERE is_active;
CREATE INDEX IF NOT EXISTS book_image_active_book_idx
    ON book_image (grimoire_id) WHERE is_active;
