-- Manager authority and editorial content management for theumst.

INSERT INTO authority (authority_id, name) VALUES
    (4, 'manager')
ON CONFLICT DO NOTHING;

INSERT INTO access (access_point) VALUES
    ('books'),
    ('media')
ON CONFLICT DO NOTHING;

INSERT INTO authority_access_map (authority_id, access_id)
SELECT a.authority_id, p.access_id
FROM authority a
JOIN access p ON
    (a.name = 'manager' AND p.access_point IN ('profile', 'api-keys', 'books', 'media'))
 OR (a.name = 'admin' AND p.access_point IN ('books', 'media'))
 OR (a.name = 'superadmin' AND p.access_point IN ('books', 'media'))
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS media_post (
    media_post_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id int REFERENCES "user"(user_id) ON DELETE SET NULL,
    title text NOT NULL CHECK (length(btrim(title)) > 0),
    slug text NOT NULL UNIQUE,
    excerpt text NOT NULL DEFAULT '',
    body text NOT NULL CHECK (length(btrim(body)) > 0),
    image_url text,
    status text NOT NULL DEFAULT 'published'
        CHECK (status IN ('draft', 'published')),
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS media_post_public_idx
    ON media_post (published_at DESC) WHERE status = 'published';

DROP TRIGGER IF EXISTS media_post_touch_updated_at ON media_post;
CREATE TRIGGER media_post_touch_updated_at
BEFORE UPDATE ON media_post
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

INSERT INTO media_post (title, slug, excerpt, body, image_url, status, published_at) VALUES
    (
        'Building a world from knowledge',
        'building-a-world-from-knowledge',
        'A first look at how structured research becomes an explorable, playable knowledge map.',
        'theumst is turning textbooks, papers, and expert insight into structured knowledge objects. Those objects can become quests, explanations, benchmarks, and training data—so learning progress and model progress can reinforce one another.',
        '/images/cave.jpg',
        'published',
        now()
    ),
    (
        'From learning graph to benchmarking ecosystem',
        'learning-graph-to-benchmarking-ecosystem',
        'Why the same structured graph can support education, model evaluation, and AI safety research.',
        'A well-grounded knowledge graph creates more than a curriculum. It creates measurable tasks, traceable evidence, and repeatable evaluations. Over time, theumst can use this foundation to compare systems, surface failure modes, and contribute to safer AI development.',
        '/images/graph.jpg',
        'published',
        now() - interval '1 day'
    )
ON CONFLICT (slug) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('authority', 'authority_id'),
    COALESCE((SELECT max(authority_id) FROM authority), 1),
    true
);
