-- One-use password recovery tokens. Raw tokens are never stored.

CREATE TABLE IF NOT EXISTS password_reset_token (
    password_reset_token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    sent_at timestamptz,
    used_at timestamptz,
    requested_ip inet,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS password_reset_token_active_idx
    ON password_reset_token (token_hash, expires_at) WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS password_reset_token_user_recent_idx
    ON password_reset_token (user_id, created_at DESC);
