-- Beta-access workflow and durable study state for Web Demo Version 0.0.1.

INSERT INTO authority (authority_id, name) VALUES (5, 'betatester')
ON CONFLICT DO NOTHING;

INSERT INTO access (access_point) VALUES ('demo')
ON CONFLICT DO NOTHING;

INSERT INTO authority_access_map (authority_id, access_id)
SELECT a.authority_id, p.access_id
FROM authority a
JOIN access p ON p.access_point IN (
    CASE
        WHEN a.name = 'betatester' THEN 'profile'
        ELSE 'demo'
    END,
    CASE
        WHEN a.name = 'betatester' THEN 'api-keys'
        ELSE 'demo'
    END,
    'demo'
)
WHERE a.name IN ('betatester', 'manager', 'admin', 'superadmin')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS demo_access_request (
    user_id int PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'rejected')),
    request_message text NOT NULL DEFAULT '',
    review_note text NOT NULL DEFAULT '',
    requested_at timestamptz NOT NULL DEFAULT now(),
    reviewed_by_user_id int REFERENCES "user"(user_id) ON DELETE SET NULL,
    reviewed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_grimoire (
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    summoned_at timestamptz NOT NULL DEFAULT now(),
    last_opened_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, grimoire_id)
);

CREATE TABLE IF NOT EXISTS demo_knowledge_progress (
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    knowledge_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    completed boolean NOT NULL DEFAULT false,
    completed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, knowledge_id)
);

CREATE TABLE IF NOT EXISTS demo_study_state (
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    current_knowledge_id int REFERENCES knowledge(knowledge_id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, grimoire_id)
);

CREATE TABLE IF NOT EXISTS demo_note (
    demo_note_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    grimoire_id int REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    knowledge_id int REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    note_type text NOT NULL CHECK (note_type IN ('attached', 'scribble')),
    tag text NOT NULL DEFAULT '',
    content text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (note_type = 'attached' AND knowledge_id IS NOT NULL)
        OR (note_type = 'scribble' AND knowledge_id IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS demo_similarity (
    from_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    to_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    statement_score numeric(5, 4) NOT NULL CHECK (statement_score BETWEEN 0 AND 1),
    combined_score numeric(5, 4) NOT NULL CHECK (combined_score BETWEEN 0 AND 1),
    PRIMARY KEY (from_id, to_id),
    CHECK (from_id <> to_id)
);

CREATE INDEX IF NOT EXISTS demo_access_request_status_idx
    ON demo_access_request (status, requested_at DESC);
CREATE INDEX IF NOT EXISTS user_grimoire_recent_idx
    ON user_grimoire (user_id, last_opened_at DESC);
CREATE INDEX IF NOT EXISTS demo_note_user_book_idx
    ON demo_note (user_id, grimoire_id, updated_at DESC);

DROP TRIGGER IF EXISTS demo_access_request_touch_updated_at ON demo_access_request;
CREATE TRIGGER demo_access_request_touch_updated_at
BEFORE UPDATE ON demo_access_request
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS demo_knowledge_progress_touch_updated_at ON demo_knowledge_progress;
CREATE TRIGGER demo_knowledge_progress_touch_updated_at
BEFORE UPDATE ON demo_knowledge_progress
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS demo_study_state_touch_updated_at ON demo_study_state;
CREATE TRIGGER demo_study_state_touch_updated_at
BEFORE UPDATE ON demo_study_state
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS demo_note_touch_updated_at ON demo_note;
CREATE TRIGGER demo_note_touch_updated_at
BEFORE UPDATE ON demo_note
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- The original beta fixtures are deliberately not recreated here. Books are
-- now managed through the catalog, so deleting a book must survive restarts.
-- The remaining idempotent statements only maintain fixtures that still exist
-- in an older installation and become no-ops once those fixtures are removed.

INSERT INTO language_grimoire
    (language_id, grimoire_id, title, is_original_language, publisher)
SELECT 1, grimoire_id, 'Foundations of Linear Algebra', true, 'UMST Demo Library'
FROM grimoire WHERE source_key = 'demo-linear-algebra-001'
ON CONFLICT (language_id, grimoire_id) DO UPDATE SET
    title = EXCLUDED.title,
    publisher = EXCLUDED.publisher;

INSERT INTO language_grimoire
    (language_id, grimoire_id, title, is_original_language, publisher)
SELECT 1, grimoire_id, 'Geometry of Change', true, 'UMST Demo Library'
FROM grimoire WHERE source_key = 'demo-calculus-001'
ON CONFLICT (language_id, grimoire_id) DO UPDATE SET
    title = EXCLUDED.title,
    publisher = EXCLUDED.publisher;

INSERT INTO section (grimoire_id, section_number, source_key, source_metadata)
SELECT grimoire_id, '1', 'demo-la-vectors', '{"demo_order":1}'::jsonb
FROM grimoire g
WHERE g.source_key = 'demo-linear-algebra-001'
  AND NOT EXISTS (
      SELECT 1 FROM section s
      WHERE s.grimoire_id = g.grimoire_id AND s.source_key = 'demo-la-vectors'
  );

INSERT INTO section (grimoire_id, parent_section, section_number, source_key, source_metadata)
SELECT g.grimoire_id, parent.section_id, '1.1', 'demo-la-language', '{"demo_order":2}'::jsonb
FROM grimoire g
JOIN section parent ON parent.grimoire_id = g.grimoire_id
    AND parent.source_key = 'demo-la-vectors'
WHERE g.source_key = 'demo-linear-algebra-001'
  AND NOT EXISTS (
      SELECT 1 FROM section s
      WHERE s.grimoire_id = g.grimoire_id AND s.source_key = 'demo-la-language'
  );

INSERT INTO section (grimoire_id, parent_section, section_number, source_key, source_metadata)
SELECT g.grimoire_id, parent.section_id, '1.1.1', 'demo-la-combinations', '{"demo_order":3}'::jsonb
FROM grimoire g
JOIN section parent ON parent.grimoire_id = g.grimoire_id
    AND parent.source_key = 'demo-la-language'
WHERE g.source_key = 'demo-linear-algebra-001'
  AND NOT EXISTS (
      SELECT 1 FROM section s
      WHERE s.grimoire_id = g.grimoire_id AND s.source_key = 'demo-la-combinations'
  );

INSERT INTO section (grimoire_id, section_number, source_key, source_metadata)
SELECT grimoire_id, '2', 'demo-la-transformations', '{"demo_order":4}'::jsonb
FROM grimoire g
WHERE g.source_key = 'demo-linear-algebra-001'
  AND NOT EXISTS (
      SELECT 1 FROM section s
      WHERE s.grimoire_id = g.grimoire_id AND s.source_key = 'demo-la-transformations'
  );

INSERT INTO section (grimoire_id, section_number, source_key, source_metadata)
SELECT grimoire_id, '1', 'demo-calc-change', '{"demo_order":1}'::jsonb
FROM grimoire g
WHERE g.source_key = 'demo-calculus-001'
  AND NOT EXISTS (
      SELECT 1 FROM section s
      WHERE s.grimoire_id = g.grimoire_id AND s.source_key = 'demo-calc-change'
  );

INSERT INTO language_section (language_id, section_id, section_name, section_head, section_tail)
SELECT 1, s.section_id,
    CASE s.source_key
        WHEN 'demo-la-vectors' THEN 'Vectors and space'
        WHEN 'demo-la-language' THEN 'The language of vectors'
        WHEN 'demo-la-combinations' THEN 'Linear combinations'
        WHEN 'demo-la-transformations' THEN 'Transformations'
        WHEN 'demo-calc-change' THEN 'Change and local linearity'
    END,
    '', ''
FROM section s
WHERE s.source_key IN (
    'demo-la-vectors', 'demo-la-language', 'demo-la-combinations',
    'demo-la-transformations', 'demo-calc-change'
)
ON CONFLICT (language_id, section_id) DO UPDATE SET
    section_name = EXCLUDED.section_name;

CREATE OR REPLACE FUNCTION seed_demo_knowledge(
    p_section_key text,
    p_source_key text,
    p_demo_order int,
    p_type text,
    p_label text,
    p_statement text,
    p_working text,
    p_working_summary text
) RETURNS int
LANGUAGE plpgsql
AS $function$
DECLARE
    v_section_id int;
    v_knowledge_id int;
    v_crystal_id int;
BEGIN
    SELECT section_id INTO v_section_id FROM section WHERE source_key = p_section_key LIMIT 1;
    IF v_section_id IS NULL THEN
        RETURN NULL;
    END IF;
    SELECT knowledge_id INTO v_knowledge_id
    FROM knowledge
    WHERE section_id = v_section_id AND source_key = p_source_key;

    IF v_knowledge_id IS NULL THEN
        INSERT INTO knowledge_crystal DEFAULT VALUES RETURNING knowledge_crystal_id INTO v_crystal_id;
        INSERT INTO knowledge
            (section_id, knowledge_crystal_id, type, is_default_in_crystal, source_key, source_metadata)
        VALUES
            (v_section_id, v_crystal_id, p_type, true, p_source_key,
             jsonb_build_object('demo', true, 'demo_order', p_demo_order))
        RETURNING knowledge_id INTO v_knowledge_id;
    ELSE
        UPDATE knowledge SET
            type = p_type,
            source_metadata = jsonb_build_object('demo', true, 'demo_order', p_demo_order)
        WHERE knowledge_id = v_knowledge_id;
    END IF;

    INSERT INTO language_knowledge
        (language_id, knowledge_id, label, statement, working, working_summary)
    VALUES
        (1, v_knowledge_id, p_label, p_statement, p_working, p_working_summary)
    ON CONFLICT (language_id, knowledge_id) DO UPDATE SET
        label = EXCLUDED.label,
        statement = EXCLUDED.statement,
        working = EXCLUDED.working,
        working_summary = EXCLUDED.working_summary;

    RETURN v_knowledge_id;
END;
$function$;

SELECT seed_demo_knowledge(
    'demo-la-language', 'demo-vector-definition', 1, 'definition', 'Definition 1.1',
    'A vector in $$\mathbb{R}^n$$ is an ordered list $$v=(v_1,\ldots,v_n)$$.',
    'Vectors encode both magnitude and direction. Two vectors are equal when every corresponding coordinate is equal.',
    'An ordered coordinate list that represents magnitude and direction.'
);
SELECT seed_demo_knowledge(
    'demo-la-language', 'demo-coordinate-notation', 2, 'notation', 'Notation 1.2',
    'We write the standard basis as $$e_1,\ldots,e_n$$, where $$(e_i)_j=\delta_{ij}$$.',
    'Every vector has the coordinate expansion $$v=\sum_{i=1}^{n}v_i e_i$$.',
    'Standard-basis notation for coordinate vectors.'
);
SELECT seed_demo_knowledge(
    'demo-la-language', 'demo-vector-context', 3, 'context', 'Context: navigation',
    'A displacement vector records how far and in which direction an object moves.',
    'Position, force, colour, and model parameters can all be represented as vectors. This branch adds meaning without interrupting the core line.',
    'A real-world interpretation of vectors as displacement.'
);
SELECT seed_demo_knowledge(
    'demo-la-combinations', 'demo-span-theorem', 4, 'theorem', 'Theorem 1.3',
    'The span of $$v_1,\ldots,v_k$$ is the set $$\{a_1v_1+\cdots+a_kv_k:a_i\in\mathbb{R}\}$$.',
    'Closure under vector addition and scalar multiplication makes a span a subspace. The coefficients describe every reachable point.',
    'Linear combinations generate the span of a vector collection.'
);
SELECT seed_demo_knowledge(
    'demo-la-combinations', 'demo-span-context', 5, 'context', 'Geometric lens',
    'Two non-parallel vectors in $$\mathbb{R}^2$$ span the whole plane.',
    'Changing either coefficient sweeps along one direction; changing both fills the plane.',
    'Geometric intuition for spanning a plane.'
);
SELECT seed_demo_knowledge(
    'demo-la-combinations', 'demo-combination-exercise', 6, 'exercise', 'Exercise 1.4',
    'Find $$a,b$$ such that $$a(1,0)+b(1,1)=(3,2)$$.',
    'Compare coordinates: $$a+b=3$$ and $$b=2$$, so $$b=2$$ and $$a=1$$.',
    'Solve a two-vector coordinate combination.'
);
SELECT seed_demo_knowledge(
    'demo-la-transformations', 'demo-linear-map-definition', 7, 'definition', 'Definition 2.1',
    'A map $$T:V\to W$$ is linear when $$T(au+bv)=aT(u)+bT(v)$$.',
    'A linear map preserves the operations that define vector spaces, so its behaviour is determined by a basis.',
    'Linearity means preserving combinations.'
);
SELECT seed_demo_knowledge(
    'demo-la-transformations', 'demo-linearity-exercise', 8, 'exercise', 'Exercise 2.2',
    'Decide whether $$T(x,y)=(2x-y,x+3y)$$ is linear.',
    'The map is multiplication by $$\begin{pmatrix}2&-1\\1&3\end{pmatrix}$$, so it preserves all linear combinations.',
    'Recognise a linear transformation from its matrix.'
);
SELECT seed_demo_knowledge(
    'demo-calc-change', 'demo-derivative-definition', 1, 'definition', 'Definition 1.1',
    'The derivative is $$f''(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}$$ when the limit exists.',
    'It is the best local linear approximation: $$f(x+h)\approx f(x)+f''(x)h$$ for small $$h$$.',
    'The derivative measures instantaneous change and local linearity.'
);
SELECT seed_demo_knowledge(
    'demo-calc-change', 'demo-gradient-context', 2, 'context', 'Connection: gradients',
    'For $$f:\mathbb{R}^n\to\mathbb{R}$$, the gradient $$\nabla f$$ points toward steepest increase.',
    'The dot product $$\nabla f(x)\cdot h$$ is the first-order change in direction $$h$$, linking calculus back to vectors.',
    'Gradients connect derivatives with vector geometry.'
);

INSERT INTO relation (from_id, to_id, type)
SELECT a.knowledge_id, b.knowledge_id, links.relation_type
FROM (VALUES
    ('demo-vector-definition', 'demo-coordinate-notation', 'sequence'),
    ('demo-coordinate-notation', 'demo-span-theorem', 'sequence'),
    ('demo-span-theorem', 'demo-combination-exercise', 'sequence'),
    ('demo-combination-exercise', 'demo-linear-map-definition', 'sequence'),
    ('demo-linear-map-definition', 'demo-linearity-exercise', 'sequence'),
    ('demo-vector-definition', 'demo-vector-context', 'context'),
    ('demo-span-theorem', 'demo-span-context', 'context')
) AS links(from_key, to_key, relation_type)
JOIN knowledge a ON a.source_key = links.from_key
JOIN knowledge b ON b.source_key = links.to_key
ON CONFLICT (from_id, to_id) DO UPDATE SET type = EXCLUDED.type;

INSERT INTO demo_similarity (from_id, to_id, statement_score, combined_score)
SELECT a.knowledge_id, b.knowledge_id, scores.statement_score, scores.combined_score
FROM (VALUES
    ('demo-vector-definition', 'demo-gradient-context', 0.8200::numeric, 0.7600::numeric),
    ('demo-linear-map-definition', 'demo-derivative-definition', 0.7900::numeric, 0.9100::numeric),
    ('demo-coordinate-notation', 'demo-gradient-context', 0.7100::numeric, 0.7300::numeric),
    ('demo-span-theorem', 'demo-derivative-definition', 0.6300::numeric, 0.6800::numeric)
) AS scores(from_key, to_key, statement_score, combined_score)
JOIN knowledge a ON a.source_key = scores.from_key
JOIN knowledge b ON b.source_key = scores.to_key
ON CONFLICT (from_id, to_id) DO UPDATE SET
    statement_score = EXCLUDED.statement_score,
    combined_score = EXCLUDED.combined_score;

DROP FUNCTION IF EXISTS seed_demo_knowledge(text, text, int, text, text, text, text, text);

SELECT setval(
    pg_get_serial_sequence('authority', 'authority_id'),
    COALESCE((SELECT max(authority_id) FROM authority), 1),
    true
);
