-- Explicit consent only: this migration never subscribes an existing account.
ALTER TABLE media_post ADD COLUMN IF NOT EXISTS email_introduction text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS news_subscription (
    user_id int PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
    email text NOT NULL,
    enabled boolean NOT NULL DEFAULT false,
    consent_id uuid NOT NULL,
    consent_at timestamptz NOT NULL DEFAULT now(),
    consent_source text NOT NULL CHECK (consent_source IN ('profile', 'login', 'unsubscribe', 'email_change')),
    confirmed_at timestamptz,
    unsubscribe_token text NOT NULL UNIQUE,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS news_consent_event (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES "user"(user_id) ON DELETE SET NULL,
    email text NOT NULL,
    enabled boolean NOT NULL,
    source text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS news_suppression (
    email text PRIMARY KEY,
    reason text NOT NULL,
    provider_email_id text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS news_announcement (
    announcement_id uuid PRIMARY KEY,
    media_post_id bigint NOT NULL UNIQUE REFERENCES media_post(media_post_id) ON DELETE CASCADE,
    title text NOT NULL,
    introduction text NOT NULL,
    created_by_user_id int REFERENCES "user"(user_id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS news_delivery (
    delivery_id uuid PRIMARY KEY,
    announcement_id uuid NOT NULL REFERENCES news_announcement(announcement_id) ON DELETE CASCADE,
    user_id int REFERENCES "user"(user_id) ON DELETE SET NULL,
    recipient_email text NOT NULL,
    consent_id uuid NOT NULL,
    payload jsonb NOT NULL,
    status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'sending', 'sent', 'delivered', 'skipped', 'failed', 'uncertain', 'bounced', 'complained', 'suppressed')),
    attempts int NOT NULL DEFAULT 0,
    first_attempt_at timestamptz,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    lease_until timestamptz,
    provider_email_id text UNIQUE,
    last_error text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (announcement_id, recipient_email)
);
CREATE INDEX IF NOT EXISTS news_delivery_due_idx ON news_delivery(next_attempt_at) WHERE status IN ('queued', 'sending');
CREATE TABLE IF NOT EXISTS news_provider_event (
    event_id text PRIMARY KEY,
    event_type text NOT NULL,
    provider_email_id text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
