CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS authority (
    authority_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS access (
    access_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_point text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS authority_access_map (
    authority_id int NOT NULL REFERENCES authority(authority_id) ON DELETE CASCADE,
    access_id int NOT NULL REFERENCES access(access_id) ON DELETE CASCADE,
    PRIMARY KEY (authority_id, access_id)
);

CREATE TABLE IF NOT EXISTS api_rate (
    api_rate_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    searches_per_hour int NOT NULL CHECK (searches_per_hour >= 0),
    level_name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS language (
    language_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS field (
    field_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_field int REFERENCES field(field_id) ON DELETE SET NULL,
    difficulty text NOT NULL
);

CREATE TABLE IF NOT EXISTS knowledge_crystal (
    knowledge_crystal_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    likes int NOT NULL DEFAULT 0 CHECK (likes >= 0)
);

CREATE TABLE IF NOT EXISTS grimoire (
    grimoire_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn text,
    publish_date text,
    version text
);

CREATE TABLE IF NOT EXISTS language_grimoire (
    language_id int NOT NULL REFERENCES language(language_id) ON DELETE CASCADE,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    PRIMARY KEY (language_id, grimoire_id),
    title text NOT NULL,
    is_original_language boolean NOT NULL,
    publisher text NOT NULL
);

CREATE TABLE IF NOT EXISTS grimoire_field (
    field_id int NOT NULL REFERENCES field(field_id) ON DELETE CASCADE,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    PRIMARY KEY (field_id, grimoire_id)
);

CREATE TABLE IF NOT EXISTS language_field (
    language_id int NOT NULL REFERENCES language(language_id) ON DELETE CASCADE,
    field_id int NOT NULL REFERENCES field(field_id) ON DELETE CASCADE,
    PRIMARY KEY (language_id, field_id),
    name text NOT NULL UNIQUE,
    description text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "class" (
    class_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id int NOT NULL UNIQUE REFERENCES field(field_id) ON DELETE CASCADE,
    name text NOT NULL UNIQUE,
    type text NOT NULL
);

CREATE TABLE IF NOT EXISTS character_data (
    character_data_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level int NOT NULL
);

CREATE TABLE IF NOT EXISTS pet_data (
    pet_data_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level int NOT NULL
);

CREATE TABLE IF NOT EXISTS "user" (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority_id int REFERENCES authority(authority_id),
    username text NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    profile_picture_url text,
    alias text,
    description text,
    email_verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS email text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'user'
          AND column_name = 'email_verified_at'
    ) THEN
        ALTER TABLE "user" ADD COLUMN email_verified_at timestamptz;
        UPDATE "user" SET email_verified_at = COALESCE(created_at, now());
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS user_username_casefold_unique
    ON "user" (lower(username));

CREATE UNIQUE INDEX IF NOT EXISTS user_email_casefold_unique
    ON "user" (lower(email));

CREATE TABLE IF NOT EXISTS "identity" (
    identity_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    identity_number text NOT NULL,
    type text NOT NULL,
    UNIQUE (user_id, type, identity_number)
);

CREATE TABLE IF NOT EXISTS web_session (
    web_session_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz
);

CREATE TABLE IF NOT EXISTS password_reset_token (
    password_reset_token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    sent_at timestamptz,
    used_at timestamptz,
    requested_ip inet,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS email_verification_token (
    email_verification_token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    sent_at timestamptz,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS email_change_token (
    email_change_token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    new_email text NOT NULL,
    token_hash text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    sent_at timestamptz,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS api_key (
    api_key_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    api_rate_id int REFERENCES api_rate(api_rate_id) ON DELETE SET NULL,
    name text NOT NULL,
    password_hash text NOT NULL DEFAULT '',
    key_prefix text NOT NULL,
    key_hash text NOT NULL UNIQUE,
    key_type text NOT NULL DEFAULT 'regular'
        CHECK (key_type IN ('regular', 'master')),
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    revoked_at timestamptz,
    upgraded_at timestamptz,
    upgraded_by_user_id int REFERENCES "user"(user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS api_rate_window (
    api_key_id int PRIMARY KEY REFERENCES api_key(api_key_id) ON DELETE CASCADE,
    window_started_at timestamptz NOT NULL DEFAULT now(),
    request_count int NOT NULL DEFAULT 0 CHECK (request_count >= 0)
);

CREATE TABLE IF NOT EXISTS section (
    section_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_section int REFERENCES section(section_id) ON DELETE SET NULL,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    section_number text NOT NULL,
    UNIQUE (grimoire_id, parent_section, section_number)
);

CREATE UNIQUE INDEX IF NOT EXISTS section_book_parent_number_unique
    ON section (grimoire_id, COALESCE(parent_section, 0), section_number);

CREATE TABLE IF NOT EXISTS language_section (
    language_id int NOT NULL REFERENCES language(language_id) ON DELETE CASCADE,
    section_id int NOT NULL REFERENCES section(section_id) ON DELETE CASCADE,
    PRIMARY KEY (language_id, section_id),
    section_name text,
    section_head text,
    section_tail text
);

CREATE TABLE IF NOT EXISTS knowledge (
    knowledge_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id int NOT NULL REFERENCES section(section_id) ON DELETE CASCADE,
    knowledge_crystal_id int NOT NULL REFERENCES knowledge_crystal(knowledge_crystal_id) ON DELETE CASCADE,
    type text NOT NULL,
    is_default_in_crystal boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS language_knowledge (
    language_id int NOT NULL REFERENCES language(language_id) ON DELETE CASCADE,
    knowledge_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    PRIMARY KEY (language_id, knowledge_id),
    working text NOT NULL DEFAULT '',
    statement text NOT NULL
);

CREATE TABLE IF NOT EXISTS voice (
    voice_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    context text NOT NULL
);

CREATE TABLE IF NOT EXISTS language_voice (
    language_id int NOT NULL REFERENCES language(language_id) ON DELETE CASCADE,
    voice_id int NOT NULL REFERENCES voice(voice_id) ON DELETE CASCADE,
    PRIMARY KEY (language_id, voice_id),
    voice_instructions text NOT NULL,
    url text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS image (
    image_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS language_image (
    language_id int NOT NULL REFERENCES language(language_id) ON DELETE CASCADE,
    image_id int NOT NULL REFERENCES image(image_id) ON DELETE CASCADE,
    PRIMARY KEY (language_id, image_id),
    url text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS relation (
    from_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    to_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    PRIMARY KEY (from_id, to_id),
    type text NOT NULL,
    CHECK (from_id <> to_id)
);

-- Clean fresh-install ingestion/content/demo contract. Historical numbered
-- migrations remain for existing installations, but production startup never
-- replays them and this file contains no sample-book or news fixtures.
ALTER TABLE grimoire ADD COLUMN IF NOT EXISTS source_key text;
ALTER TABLE grimoire ADD COLUMN IF NOT EXISTS source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE UNIQUE INDEX IF NOT EXISTS grimoire_source_key_unique
    ON grimoire (source_key) WHERE source_key IS NOT NULL;

ALTER TABLE section ADD COLUMN IF NOT EXISTS source_key text;
ALTER TABLE section ADD COLUMN IF NOT EXISTS source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE UNIQUE INDEX IF NOT EXISTS section_book_source_key_unique
    ON section (grimoire_id, source_key) WHERE source_key IS NOT NULL;

ALTER TABLE knowledge ADD COLUMN IF NOT EXISTS source_key text;
ALTER TABLE knowledge ADD COLUMN IF NOT EXISTS source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE knowledge ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
CREATE UNIQUE INDEX IF NOT EXISTS knowledge_section_source_key_unique
    ON knowledge (section_id, source_key) WHERE source_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS knowledge_active_source_idx
    ON knowledge (section_id, source_key) WHERE is_active;

ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS label text;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS working_summary text;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS ref_id text;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS labelled_references jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS object_reference_labels jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS loose_references_guessed_objects jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE language_knowledge ADD COLUMN IF NOT EXISTS source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS book_image (
    book_image_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    section_id int REFERENCES section(section_id) ON DELETE SET NULL,
    knowledge_id int REFERENCES knowledge(knowledge_id) ON DELETE SET NULL,
    source_image_id text NOT NULL,
    semantic_context_name text,
    storage_key text NOT NULL,
    url text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    UNIQUE (grimoire_id, source_image_id)
);
CREATE INDEX IF NOT EXISTS book_image_knowledge_idx ON book_image (knowledge_id);
CREATE INDEX IF NOT EXISTS book_image_section_idx ON book_image (section_id);
CREATE INDEX IF NOT EXISTS book_image_active_book_idx
    ON book_image (grimoire_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS media_post (
    media_post_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id int REFERENCES "user"(user_id) ON DELETE SET NULL,
    grimoire_id bigint REFERENCES grimoire(grimoire_id) ON DELETE RESTRICT,
    title text NOT NULL CHECK (length(btrim(title)) > 0),
    slug text NOT NULL UNIQUE,
    excerpt text NOT NULL DEFAULT '',
    body text NOT NULL CHECK (length(btrim(body)) > 0),
    image_url text,
    status text NOT NULL DEFAULT 'published' CHECK (status IN ('draft', 'published')),
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS media_post_public_idx
    ON media_post (published_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS media_post_grimoire_idx
    ON media_post (grimoire_id) WHERE grimoire_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS demo_access_request (
    user_id int PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    request_message text NOT NULL DEFAULT '',
    review_note text NOT NULL DEFAULT '',
    requested_at timestamptz NOT NULL DEFAULT now(),
    reviewed_by_user_id int REFERENCES "user"(user_id) ON DELETE SET NULL,
    reviewed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS user_grimoire (
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    summoned_at timestamptz NOT NULL DEFAULT now(),
    last_opened_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, grimoire_id)
);
CREATE TABLE IF NOT EXISTS demo_knowledge_progress (
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    knowledge_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    completed boolean NOT NULL DEFAULT false,
    completed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, knowledge_id)
);
CREATE TABLE IF NOT EXISTS demo_study_state (
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    current_knowledge_id int REFERENCES knowledge(knowledge_id) ON DELETE SET NULL,
    questions_knowledge_id int REFERENCES knowledge(knowledge_id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, grimoire_id)
);
CREATE TABLE IF NOT EXISTS demo_note (
    demo_note_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    grimoire_id int REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    knowledge_id int REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    note_type text NOT NULL CHECK (note_type IN ('attached', 'scribble')),
    tag text NOT NULL DEFAULT '',
    content text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((note_type = 'attached' AND knowledge_id IS NOT NULL)
        OR (note_type = 'scribble' AND knowledge_id IS NULL))
);
CREATE TABLE IF NOT EXISTS demo_similarity (
    from_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    to_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    statement_score numeric(5, 4) NOT NULL CHECK (statement_score BETWEEN 0 AND 1),
    combined_score numeric(5, 4) NOT NULL CHECK (combined_score BETWEEN 0 AND 1),
    PRIMARY KEY (from_id, to_id),
    CHECK (from_id <> to_id)
);
CREATE INDEX IF NOT EXISTS demo_access_request_status_idx
    ON demo_access_request (status, requested_at DESC);
CREATE INDEX IF NOT EXISTS user_grimoire_recent_idx
    ON user_grimoire (user_id, last_opened_at DESC);
CREATE INDEX IF NOT EXISTS demo_note_user_book_idx
    ON demo_note (user_id, grimoire_id, updated_at DESC);

-- Optional, versioned knowledge-graph sidecar support. The legacy relation
-- table remains untouched. Existing books deliberately stay "unavailable"
-- until an approved sidecar explicitly supplies stable identities, semantic
-- roles, and relations; nothing is inferred from order, type, proximity,
-- references, or embedding similarity.
ALTER TABLE grimoire ADD COLUMN IF NOT EXISTS graph_contract_version int;
ALTER TABLE grimoire ADD COLUMN IF NOT EXISTS graph_revision text NOT NULL DEFAULT '';
ALTER TABLE grimoire ADD COLUMN IF NOT EXISTS graph_capability text NOT NULL DEFAULT 'unavailable'
    CHECK (graph_capability IN ('unavailable', 'semantic_relations', 'relations_declared_empty'));
ALTER TABLE grimoire ADD COLUMN IF NOT EXISTS graph_receipt_id text;

CREATE TABLE IF NOT EXISTS knowledge_graph_node (
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    knowledge_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    stable_knowledge_id text NOT NULL,
    graph_role text NOT NULL
        CHECK (graph_role IN ('backbone', 'support', 'assessment', 'fragment', 'crosslink')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (grimoire_id, stable_knowledge_id),
    UNIQUE (grimoire_id, knowledge_id)
);

CREATE TABLE IF NOT EXISTS knowledge_graph_edge (
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    source_knowledge_id int NOT NULL,
    target_knowledge_id int NOT NULL,
    relation_type text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (grimoire_id, source_knowledge_id, target_knowledge_id, relation_type),
    FOREIGN KEY (grimoire_id, source_knowledge_id)
        REFERENCES knowledge_graph_node(grimoire_id, knowledge_id) ON DELETE CASCADE,
    FOREIGN KEY (grimoire_id, target_knowledge_id)
        REFERENCES knowledge_graph_node(grimoire_id, knowledge_id) ON DELETE CASCADE,
    CHECK (source_knowledge_id <> target_knowledge_id),
    CHECK (relation_type ~ '^[a-z][a-z0-9_.:-]*$')
);

CREATE TABLE IF NOT EXISTS knowledge_graph_receipt (
    receipt_id text NOT NULL,
    grimoire_id int NOT NULL REFERENCES grimoire(grimoire_id) ON DELETE CASCADE,
    book_source_key text NOT NULL,
    contract_version int NOT NULL CHECK (contract_version > 0),
    graph_revision text NOT NULL,
    sidecar_digest text NOT NULL,
    capability text NOT NULL
        CHECK (capability IN ('semantic_relations', 'relations_declared_empty')),
    node_count int NOT NULL CHECK (node_count >= 0),
    relation_count int NOT NULL CHECK (relation_count >= 0),
    diagnostics jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(diagnostics) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (grimoire_id, receipt_id)
);

CREATE INDEX IF NOT EXISTS knowledge_graph_edge_source_idx
    ON knowledge_graph_edge (grimoire_id, source_knowledge_id, relation_type, target_knowledge_id);
CREATE INDEX IF NOT EXISTS knowledge_graph_edge_target_idx
    ON knowledge_graph_edge (grimoire_id, target_knowledge_id, relation_type, source_knowledge_id);
CREATE INDEX IF NOT EXISTS knowledge_graph_receipt_book_idx
    ON knowledge_graph_receipt (grimoire_id, created_at DESC);
CREATE INDEX IF NOT EXISTS section_book_parent_idx
    ON section (grimoire_id, parent_section, section_id);

CREATE TABLE IF NOT EXISTS similarity (
    from_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    to_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    PRIMARY KEY (from_id, to_id),
    rank text NOT NULL,
    CHECK (from_id <> to_id)
);

CREATE TABLE IF NOT EXISTS label (
    label_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id int NOT NULL REFERENCES section(section_id) ON DELETE CASCADE,
    name text NOT NULL,
    context text NOT NULL
);

CREATE TABLE IF NOT EXISTS "reference" (
    reference_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    type text NOT NULL,
    label_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS knowledge_field (
    knowledge_id int NOT NULL REFERENCES knowledge(knowledge_id) ON DELETE CASCADE,
    field_id int NOT NULL REFERENCES field(field_id) ON DELETE CASCADE,
    PRIMARY KEY (knowledge_id, field_id)
);

CREATE TABLE IF NOT EXISTS "character" (
    character_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    character_data_id int NOT NULL REFERENCES character_data(character_data_id) ON DELETE CASCADE,
    class_id int NOT NULL REFERENCES "class"(class_id) ON DELETE CASCADE,
    alias text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS pet (
    pet_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id int NOT NULL REFERENCES "character"(character_id) ON DELETE CASCADE,
    class_id int NOT NULL REFERENCES "class"(class_id) ON DELETE CASCADE,
    pet_data_id int NOT NULL REFERENCES pet_data(pet_data_id) ON DELETE CASCADE,
    elo int NOT NULL,
    evolution int NOT NULL
);

CREATE TABLE IF NOT EXISTS embedding_model (
    embedding_model_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    model_name text NOT NULL,
    model_revision text NOT NULL DEFAULT '',
    vector_size int NOT NULL CHECK (vector_size > 0),
    distance_metric text NOT NULL DEFAULT 'cosine'
        CHECK (distance_metric IN ('cosine', 'dot', 'euclid')),
    qdrant_collection text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, model_name, model_revision)
);

CREATE TABLE IF NOT EXISTS semantic_projection (
    semantic_projection_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id int NOT NULL,
    language_id int NOT NULL,
    projection_type text NOT NULL,
    direction text NOT NULL CHECK (direction IN ('self', 'outward', 'inward')),
    target_description text NOT NULL,
    embedding_text text NOT NULL,
    target_concepts text[] NOT NULL DEFAULT ARRAY[]::text[],
    expected_target_types text[] NOT NULL DEFAULT ARRAY[]::text[],
    specificity text NOT NULL DEFAULT 'conceptual'
        CHECK (specificity IN ('specific', 'conceptual', 'broad')),
    grounding_kind text NOT NULL DEFAULT 'strong_inference'
        CHECK (grounding_kind IN ('explicit', 'strong_inference', 'speculative')),
    confidence numeric(4, 3)
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    evidence jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(evidence) = 'array'),
    structured_object jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(structured_object) = 'object'),
    generation_model text,
    generation_prompt_version text,
    content_hash char(64) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (language_id, knowledge_id)
        REFERENCES language_knowledge(language_id, knowledge_id) ON DELETE CASCADE,
    UNIQUE (knowledge_id, language_id, projection_type, direction, content_hash)
);

CREATE TABLE IF NOT EXISTS embedding (
    embedding_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    semantic_projection_id bigint NOT NULL REFERENCES semantic_projection(semantic_projection_id) ON DELETE CASCADE,
    embedding_model_id int NOT NULL REFERENCES embedding_model(embedding_model_id) ON DELETE RESTRICT,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'indexing', 'indexed', 'failed', 'deleted')),
    vector_checksum char(64),
    payload_version int NOT NULL DEFAULT 1 CHECK (payload_version > 0),
    indexed_at timestamptz,
    deleted_at timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (semantic_projection_id, embedding_model_id)
);

-- Additive upgrades for databases created by older website versions.
ALTER TABLE api_key ADD COLUMN IF NOT EXISTS api_rate_id int REFERENCES api_rate(api_rate_id) ON DELETE SET NULL;
ALTER TABLE api_key ADD COLUMN IF NOT EXISTS password_hash text NOT NULL DEFAULT '';
ALTER TABLE api_key ADD COLUMN IF NOT EXISTS key_type text NOT NULL DEFAULT 'regular';
ALTER TABLE api_key ADD COLUMN IF NOT EXISTS upgraded_at timestamptz;
ALTER TABLE api_key ADD COLUMN IF NOT EXISTS upgraded_by_user_id int REFERENCES "user"(user_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS web_session_active_idx
    ON web_session (token_hash, expires_at) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS password_reset_token_active_idx
    ON password_reset_token (token_hash, expires_at) WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS password_reset_token_user_recent_idx
    ON password_reset_token (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS email_verification_token_active_idx
    ON email_verification_token (token_hash, expires_at) WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS email_verification_token_user_recent_idx
    ON email_verification_token (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS email_change_token_active_idx
    ON email_change_token (token_hash, expires_at) WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS email_change_token_user_recent_idx
    ON email_change_token (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS api_key_active_hash_idx
    ON api_key (key_hash) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS knowledge_section_idx ON knowledge (section_id, type);
CREATE INDEX IF NOT EXISTS semantic_projection_knowledge_idx
    ON semantic_projection (knowledge_id, language_id);
CREATE INDEX IF NOT EXISTS semantic_projection_relation_idx
    ON semantic_projection (projection_type, direction);
CREATE INDEX IF NOT EXISTS semantic_projection_active_idx
    ON semantic_projection (knowledge_id, language_id) WHERE is_active;
CREATE INDEX IF NOT EXISTS semantic_projection_target_concepts_gin
    ON semantic_projection USING gin (target_concepts);
CREATE INDEX IF NOT EXISTS semantic_projection_expected_types_gin
    ON semantic_projection USING gin (expected_target_types);
CREATE INDEX IF NOT EXISTS semantic_projection_structured_object_gin
    ON semantic_projection USING gin (structured_object);
CREATE INDEX IF NOT EXISTS embedding_status_idx ON embedding (status, embedding_model_id);

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS media_post_touch_updated_at ON media_post;
CREATE TRIGGER media_post_touch_updated_at
BEFORE UPDATE ON media_post
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS demo_access_request_touch_updated_at ON demo_access_request;
CREATE TRIGGER demo_access_request_touch_updated_at
BEFORE UPDATE ON demo_access_request
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS demo_knowledge_progress_touch_updated_at ON demo_knowledge_progress;
CREATE TRIGGER demo_knowledge_progress_touch_updated_at
BEFORE UPDATE ON demo_knowledge_progress
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS demo_study_state_touch_updated_at ON demo_study_state;
CREATE TRIGGER demo_study_state_touch_updated_at
BEFORE UPDATE ON demo_study_state
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS demo_note_touch_updated_at ON demo_note;
CREATE TRIGGER demo_note_touch_updated_at
BEFORE UPDATE ON demo_note
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS semantic_projection_touch_updated_at ON semantic_projection;
CREATE TRIGGER semantic_projection_touch_updated_at
BEFORE UPDATE ON semantic_projection
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS embedding_touch_updated_at ON embedding;
CREATE TRIGGER embedding_touch_updated_at
BEFORE UPDATE ON embedding
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

INSERT INTO authority (authority_id, name) VALUES
    (1, 'user'),
    (2, 'admin'),
    (3, 'superadmin'),
    (4, 'manager'),
    (5, 'betatester')
ON CONFLICT DO NOTHING;

INSERT INTO access (access_point) VALUES
    ('profile'),
    ('api-keys'),
    ('admin'),
    ('superadmin'),
    ('books'),
    ('media'),
    ('demo')
ON CONFLICT DO NOTHING;

INSERT INTO authority_access_map (authority_id, access_id)
SELECT a.authority_id, p.access_id
FROM authority a
JOIN access p ON
    (a.name = 'user' AND p.access_point IN ('profile', 'api-keys'))
 OR (a.name = 'betatester' AND p.access_point IN ('profile', 'api-keys', 'demo'))
 OR (a.name = 'manager' AND p.access_point IN ('profile', 'api-keys', 'books', 'media', 'demo'))
 OR (a.name = 'admin' AND p.access_point IN ('profile', 'api-keys', 'admin', 'books', 'media', 'demo'))
 OR (a.name = 'superadmin' AND p.access_point IN ('profile', 'api-keys', 'admin', 'superadmin', 'books', 'media', 'demo'))
ON CONFLICT DO NOTHING;

INSERT INTO api_rate (api_rate_id, searches_per_hour, level_name) VALUES
    (1, 120, 'standard')
ON CONFLICT (level_name) DO UPDATE SET searches_per_hour = EXCLUDED.searches_per_hour;

INSERT INTO language (language_id, name) VALUES
    (1, 'English'),
    (2, 'Chinese'),
    (3, 'Japanese')
ON CONFLICT DO NOTHING;

UPDATE "user" SET authority_id = 1 WHERE authority_id IS NULL;
UPDATE api_key SET api_rate_id = 1 WHERE api_rate_id IS NULL AND key_type = 'regular';

SELECT setval(
    pg_get_serial_sequence('authority', 'authority_id'),
    COALESCE((SELECT max(authority_id) FROM authority), 1),
    true
);
SELECT setval(
    pg_get_serial_sequence('api_rate', 'api_rate_id'),
    COALESCE((SELECT max(api_rate_id) FROM api_rate), 1),
    true
);
SELECT setval(
    pg_get_serial_sequence('language', 'language_id'),
    COALESCE((SELECT max(language_id) FROM language), 1),
    true
);

CREATE OR REPLACE VIEW embedding_queue AS
SELECT
    e.embedding_id,
    e.status,
    e.payload_version,
    em.embedding_model_id,
    em.provider,
    em.model_name,
    em.model_revision,
    em.vector_size,
    em.distance_metric,
    em.qdrant_collection,
    sp.semantic_projection_id,
    sp.knowledge_id,
    sp.language_id,
    sp.projection_type,
    sp.direction,
    sp.embedding_text,
    sp.target_concepts,
    sp.expected_target_types,
    sp.specificity,
    sp.grounding_kind,
    sp.confidence,
    sp.content_hash,
    sp.structured_object,
    k.section_id,
    k.type AS working_type,
    s.grimoire_id,
    COALESCE(
        (SELECT array_agg(kf.field_id ORDER BY kf.field_id)
         FROM knowledge_field kf
         WHERE kf.knowledge_id = sp.knowledge_id),
        ARRAY[]::int[]
    ) AS field_ids
FROM embedding e
JOIN embedding_model em ON em.embedding_model_id = e.embedding_model_id
JOIN semantic_projection sp ON sp.semantic_projection_id = e.semantic_projection_id
JOIN knowledge k ON k.knowledge_id = sp.knowledge_id
JOIN section s ON s.section_id = k.section_id
WHERE e.status IN ('pending', 'failed')
  AND em.is_active
  AND sp.is_active;
