CREATE TABLE IF NOT EXISTS authority (
    authority_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "user" (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority_id int REFERENCES authority(authority_id),
    username text NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    profile_picture_url text,
    alias text,
    description text,
    created_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS web_session (
    web_session_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES "user"(user_id),
    token_hash text NOT NULL UNIQUE,
    created_at timestamp NOT NULL DEFAULT now(),
    expires_at timestamp NOT NULL,
    revoked_at timestamp
);

CREATE TABLE IF NOT EXISTS api_rate (
    api_rate_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    searches_per_hour int NOT NULL,
    level_name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS api_key (
    api_key_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES "user"(user_id),
    name text NOT NULL,
    password_hash text NOT NULL,
    key_prefix text NOT NULL,
    key_hash text NOT NULL UNIQUE,
    created_at timestamp NOT NULL DEFAULT now(),
    last_used_at timestamp,
    revoked_at timestamp
);

INSERT INTO authority (authority_id, name) VALUES
    (1, 'user'),
    (2, 'admin'),
    (3, 'superadmin')
ON CONFLICT DO NOTHING;

INSERT INTO api_rate (api_rate_id, searches_per_hour, level_name) VALUES
    (1, 120, 'standard')
ON CONFLICT DO NOTHING;
