import { computed, ref } from "vue";

const htmlLang = { en: "en", zh: "zh-CN", ja: "ja" };

const en = {
  language: "Language", chooseLanguage: "Choose your language", chooseLanguageText: "Select the language to use in the dashboard.",
  home: "Home", profile: "Profile", apiKeys: "API Keys", demo: "Web Demo", books: "Books", users: "Users", media: "Media", admin: "Operations", superadmin: "Database", signOut: "Sign out",
  dateLocale: "en-GB", roleUser: "User", roleBetatester: "Beta tester", roleManager: "Manager", roleStaff: "Staff", roleAdmin: "Staff", roleSuperadmin: "Staff", fileTypeFile: "File", fileTypeFolder: "Folder",
  identity: "Knowledge identity", profileTitle: "Profile", profileText: "Update the public details attached to your UMST account.",
  username: "Username", email: "Email", alias: "Alias", description: "Description", saveProfile: "Save profile", saved: "Profile saved.", authorityType: "Account type", accountType: "Account type",
  accountSecurity: "Account security", changeEmail: "Change email address", changeEmailText: "Your current address stays active until you confirm a one-use link sent to the new address. Your current password is required, and confirming the change signs out existing sessions.", newEmail: "New email address", currentPassword: "Current password", sendEmailChange: "Send confirmation link", emailChangeSent: "A confirmation link has been sent to the new address. Your current email remains unchanged until confirmation.",
  developer: "Developer access", apiTitle: "API Keys", apiText: "Regular keys provide rate-limited read access. Eligible staff accounts may upgrade their own keys to unlimited master keys for ingestion and storage writes.",
  keyName: "Key name", keyNameRequired: "Please enter a key name.", createKey: "Create API key", newKey: "New key:", active: "Active", revoked: "Revoked", revoke: "Revoke",
  regularKey: "Regular key", masterKey: "Master key", requestsPerHour: "requests/hour", unlimitedMaster: "Unlimited read, knowledge submission, embedding, and storage-write access.",
  upgradeMaster: "Upgrade to master", upgradeMasterConfirm: "Upgrade this key to an unlimited master key? This cannot be undone from the dashboard.", masterUpgraded: "API key upgraded to master.",
  adminTitle: "System operations", adminText: "Search semantic projections in Qdrant and manage object storage. Direct database tools are kept in the separate database workspace.",
  vectorSearch: "Semantic search", qdrantTitle: "Qdrant search", qdrantText: "Search by text when an embedding provider is configured, or paste a vector directly.",
  queryText: "Query text", queryTextPlaceholder: "What is this an example of?", queryVector: "Query vector (optional)", filtersJson: "Payload filters as JSON", resultLimit: "Result limit", searchQdrant: "Search Qdrant", invalidJson: "Invalid JSON",
  files: "Files", objectStorage: "Object Storage", storageText: "This interface is connected to SERVER=", refresh: "Refresh", up: "Up", newFolder: "New folder name", createFolder: "Create folder", newFile: "New text file", upload: "Upload file", download: "Download", delete: "Delete", emptyFolder: "This folder is empty.", filePath: "File path", fileContent: "Text content", saveFile: "Save file",
  storageLoaded: "Storage loaded.", storageFileLoaded: "File loaded.", storagePathRequired: "Please enter a file path.", storageSaved: "File saved.", folderNameRequired: "Please enter a folder name.", folderCreated: "Folder created.", fileUploaded: "File uploaded.", deleteConfirm: "Delete", deleted: "Deleted.", newFileReady: "Enter a path and content, then save.",
  teamAccess: "Team access", managerAccessTitle: "Manager access", managerAccessText: "Managers can maintain the book catalog and newsroom. They do not receive database, semantic-search, object-storage, or infrastructure access.", usernameOrEmail: "Username or email", makeManager: "Make manager", managerGranted: "is now a manager.",
  libraryOperations: "Library operations", booksTitle: "Books", booksText: "Maintain the source catalog that feeds the structured knowledge and AI training ecosystem.", booksTracked: "books tracked", sectionsMapped: "sections mapped", knowledgeObjects: "knowledge objects", newEntry: "New entry", editing: "Editing", addBook: "Add book", editBook: "Edit book", cancel: "Cancel", bookTitle: "Title", bookTitlePlaceholder: "e.g. Linear Algebra Done Right", publisher: "Publisher", isbn: "ISBN", publishDate: "Publish date", version: "Version", sourceKey: "Source key", saveChanges: "Save changes", catalog: "Catalog", currentBooks: "Current books", unknownPublisher: "Publisher not set", dateNotSet: "Date not set", sections: "sections", objects: "objects", edit: "Edit", noBooks: "No books yet", noBooksText: "Add the first source book using the form.", bookSaved: "Book saved.", bookDeleted: "Book and its connected content deleted.", deleteBookConfirm: "Permanently delete", demoEnabled: "Visible in demo", demoDisabled: "Hidden from demo", enableDemo: "Enable demo", disableDemo: "Disable demo", enableDemoConfirm: "Make this book available in the Web Demo", disableDemoConfirm: "Remove this book from the Web Demo", demoBookEnabled: "Book enabled in the Web Demo.", demoBookDisabled: "Book removed from the Web Demo.",
  accountOperations: "Account operations", usersTitle: "Users", usersText: "Review account details, access activity, developer keys, and beta requests.", totalAccounts: "total accounts", pendingDemoRequests: "pending demo requests", activeApiKeys: "active API keys", searchAccounts: "Search accounts", searchAccountsPlaceholder: "Username, alias, or email", results: "results", account: "Account", demoAccess: "Demo access", lastSession: "Last session", joined: "Joined", never: "Never", notRequested: "Not requested", usersLoading: "Loading users…", noUsers: "No users found", noUsersText: "Try a different account search.",
  editorialDesk: "Editorial desk", mediaTitle: "Media", mediaText: "Publish updates here and they appear automatically on the public website.", newStory: "New story", editPost: "Edit post", publishUpdate: "Publish an update", headline: "Headline", headlinePlaceholder: "What should the community know?", excerpt: "Summary", excerptPlaceholder: "A concise introduction for the news card.", story: "Story", storyPlaceholder: "Write the full update…", imageUrl: "Image URL", status: "Status", published: "Published", draft: "Draft", publishNow: "Publish now", saveDraft: "Save draft", newsroom: "Newsroom", allPosts: "All posts", noPosts: "No posts yet", noPostsText: "Create the first public update using the form.", postSaved: "Post saved. Published posts are now live.", postDeleted: "Post deleted.", deletePostConfirm: "Delete",
  superadminTitle: "Database tools", superadminText: "Grant staff access and perform restricted infrastructure operations.", userToPromote: "User", giveAdmin: "Grant staff access", adminGranted: "now has staff access.",
  superSql: "Database administration", superSqlTitle: "Direct PostgreSQL", superSqlText: "This executes exactly the PostgreSQL supplied below and is limited to specifically authorised staff.", sqlCode: "SQL code", runSql: "Run SQL",
  demoProgram: "Private beta programme", demoTitle: "The learning world is taking shape.", demoText: "Explore structured books as interactive grimoires, follow knowledge through a living graph, and help shape the foundation of the UMST learning and AI-training ecosystem.", demoLoading: "Loading demo access…", demoYourAccess: "Your access", demoReady: "Your grimoire awaits", demoReadyText: "You are authorised for the Web Demo. Enter the isolated study environment and continue where you left off.", demoPending: "Request under review", demoPendingText: "The team will review your beta request. Your Enter button will activate automatically after approval.", demoLocked: "Private beta access", demoLockedText: "Request access to take part in the first structured-learning experience.", demoEnter: "Enter Web Demo", demoBetaAccess: "Beta access", demoRequestReceived: "Request received", demoRequestReceivedText: "Your request is safely in the review queue.", demoRequestTitle: "Request an invitation", demoRequestText: "Tell the team what you would like to explore. A short message is optional.", demoRequestMessage: "Message", demoRequestPlaceholder: "I would like to test the knowledge graph and notes workflow…", demoRequestAgain: "Request again", demoRequestButton: "Request access", demoAwaitingReview: "Awaiting review", demoRequestSent: "Demo access request sent.", demoReviewQueue: "Review queue", demoAccessRequests: "Demo access requests", demoPendingCount: "pending", demoApprovedCount: "approved", demoTotalCount: "total", demoNoMessage: "No message supplied.", demoReject: "Reject", demoApprove: "Approve", demoApproved: "Beta access approved.", demoRejected: "Beta access request rejected.", demoNoRequests: "No requests yet", demoNoRequestsText: "New beta requests will appear here automatically."
};

const zh = {
  ...en,
  language: "语言", chooseLanguage: "选择语言", chooseLanguageText: "选择控制台使用的语言。",
  home: "首页", profile: "个人资料", apiKeys: "API 密钥", demo: "网页演示", books: "书籍", users: "用户", media: "媒体", admin: "系统运营", superadmin: "数据库", signOut: "退出登录",
  dateLocale: "zh-CN", roleUser: "用户", roleBetatester: "内测用户", roleManager: "经理", roleStaff: "工作人员", roleAdmin: "工作人员", roleSuperadmin: "工作人员", fileTypeFile: "文件", fileTypeFolder: "文件夹",
  identity: "知识身份", profileTitle: "个人资料", profileText: "更新与你的 UMST 账户关联的公开信息。", username: "用户名", email: "邮箱", alias: "昵称", description: "简介", saveProfile: "保存资料", saved: "资料已保存。", authorityType: "账户类型", accountType: "账户类型",
  accountSecurity: "账户安全", changeEmail: "更改邮箱地址", changeEmailText: "确认发送到新地址的一次性链接前，当前地址保持有效。操作需要当前密码，确认后现有会话将退出。", newEmail: "新邮箱地址", currentPassword: "当前密码", sendEmailChange: "发送确认链接", emailChangeSent: "确认链接已发送到新地址；确认前当前邮箱保持不变。",
  developer: "开发者访问", apiTitle: "API 密钥", apiText: "普通密钥提供限速读取。符合条件的工作人员账户可以将自己的密钥升级为不限速的主密钥，用于提交知识、嵌入和写入存储。",
  keyName: "密钥名称", keyNameRequired: "请输入密钥名称。", createKey: "创建 API 密钥", newKey: "新密钥：", active: "启用", revoked: "已撤销", revoke: "撤销", regularKey: "普通密钥", masterKey: "主密钥", requestsPerHour: "次请求/小时", unlimitedMaster: "不限速读取、知识提交、嵌入和存储写入。", upgradeMaster: "升级为主密钥", upgradeMasterConfirm: "将此密钥升级为不限速主密钥？控制台中无法撤销。", masterUpgraded: "API 密钥已升级为主密钥。",
  adminTitle: "系统运营", adminText: "在 Qdrant 中搜索语义投影并管理对象存储。数据库工具位于单独的数据库工作区。", vectorSearch: "语义搜索", qdrantTitle: "Qdrant 搜索", qdrantText: "配置嵌入提供商后可用文本搜索，也可以直接粘贴向量。", queryText: "查询文本", queryTextPlaceholder: "这是什么的例子？", queryVector: "查询向量（可选）", filtersJson: "JSON 载荷过滤器", resultLimit: "结果数量", searchQdrant: "搜索 Qdrant", invalidJson: "JSON 无效",
  files: "文件", objectStorage: "对象存储", storageText: "当前连接到 SERVER=", refresh: "刷新", up: "上一级", newFolder: "新文件夹名称", createFolder: "创建文件夹", newFile: "新建文本文件", upload: "上传文件", download: "下载", delete: "删除", emptyFolder: "这个文件夹是空的。", filePath: "文件路径", fileContent: "文本内容", saveFile: "保存文件", storageLoaded: "存储已加载。", storageFileLoaded: "文件已加载。", storagePathRequired: "请输入文件路径。", storageSaved: "文件已保存。", folderNameRequired: "请输入文件夹名称。", folderCreated: "文件夹已创建。", fileUploaded: "文件已上传。", deleteConfirm: "删除", deleted: "已删除。", newFileReady: "请输入路径和内容，然后保存。",
  teamAccess: "团队权限", managerAccessTitle: "经理权限", managerAccessText: "经理可以维护书籍目录和新闻中心，但不能访问数据库、语义搜索、对象存储或基础设施功能。", usernameOrEmail: "用户名或邮箱", makeManager: "设为经理", managerGranted: "已成为经理。",
  libraryOperations: "书库运营", booksTitle: "书籍", booksText: "维护为结构化知识和 AI 训练生态系统提供来源的书籍目录。", booksTracked: "本书", sectionsMapped: "个章节已映射", knowledgeObjects: "个知识对象", newEntry: "新条目", editing: "正在编辑", addBook: "添加书籍", editBook: "编辑书籍", cancel: "取消", bookTitle: "书名", bookTitlePlaceholder: "例如：《线性代数应该这样学》", publisher: "出版社", isbn: "ISBN", publishDate: "出版日期", version: "版本", sourceKey: "来源标识", saveChanges: "保存更改", catalog: "目录", currentBooks: "当前书籍", unknownPublisher: "未设置出版社", dateNotSet: "未设置日期", sections: "个章节", objects: "个对象", edit: "编辑", noBooks: "暂无书籍", noBooksText: "使用表单添加第一本来源书籍。", bookSaved: "书籍已保存。", bookDeleted: "书籍及其关联内容已删除。", deleteBookConfirm: "永久删除", demoEnabled: "演示中可见", demoDisabled: "演示中隐藏", enableDemo: "启用演示", disableDemo: "停用演示", enableDemoConfirm: "在网页演示中显示此书", disableDemoConfirm: "从网页演示中移除此书", demoBookEnabled: "书籍已在网页演示中启用。", demoBookDisabled: "书籍已从网页演示中移除。",
  accountOperations: "账户运营", usersTitle: "用户", usersText: "查看账户详情、访问活动、开发者密钥和内测申请。", totalAccounts: "账户总数", pendingDemoRequests: "待处理演示申请", activeApiKeys: "有效 API 密钥", searchAccounts: "搜索账户", searchAccountsPlaceholder: "用户名、昵称或邮箱", results: "条结果", account: "账户", demoAccess: "演示权限", lastSession: "最近会话", joined: "加入时间", never: "从未", notRequested: "未申请", usersLoading: "正在加载用户…", noUsers: "未找到用户", noUsersText: "请尝试其他搜索条件。",
  editorialDesk: "编辑工作台", mediaTitle: "媒体", mediaText: "在这里发布动态，内容会自动显示在公开网站上。", newStory: "新文章", editPost: "编辑文章", publishUpdate: "发布动态", headline: "标题", headlinePlaceholder: "希望社区了解什么？", excerpt: "摘要", excerptPlaceholder: "为新闻卡片撰写简洁的导语。", story: "正文", storyPlaceholder: "撰写完整动态…", imageUrl: "图片网址", status: "状态", published: "已发布", draft: "草稿", publishNow: "立即发布", saveDraft: "保存草稿", newsroom: "新闻中心", allPosts: "全部文章", noPosts: "暂无文章", noPostsText: "使用表单创建第一篇公开动态。", postSaved: "文章已保存，已发布的内容现已上线。", postDeleted: "文章已删除。", deletePostConfirm: "删除",
  superadminTitle: "数据库工具", superadminText: "授予工作人员权限并执行受控的基础设施操作。", userToPromote: "用户", giveAdmin: "授予工作人员权限", adminGranted: "现在拥有工作人员权限。", superSql: "数据库管理", superSqlTitle: "直接 PostgreSQL", superSqlText: "这里会执行你提供的 PostgreSQL，并仅向获明确授权的工作人员开放。", sqlCode: "SQL 代码", runSql: "运行 SQL",
  demoProgram: "私人内测计划", demoTitle: "学习世界正在成形。", demoText: "把结构化书籍作为互动魔典探索，沿着动态知识图谱前进，并参与塑造 UMST 学习与 AI 训练生态系统的基础。", demoLoading: "正在加载演示权限…", demoYourAccess: "你的权限", demoReady: "魔典正在等你", demoReadyText: "你已获准进入网页演示。进入隔离的学习环境，并从上次的位置继续。", demoPending: "请求审核中", demoPendingText: "团队将审核你的内测请求。批准后，“进入”按钮会自动启用。", demoLocked: "私人内测权限", demoLockedText: "申请加入首个结构化学习体验。", demoEnter: "进入网页演示", demoBetaAccess: "内测权限", demoRequestReceived: "请求已收到", demoRequestReceivedText: "你的请求已安全进入审核队列。", demoRequestTitle: "申请邀请", demoRequestText: "告诉团队你想探索什么；留言可以留空。", demoRequestMessage: "留言", demoRequestPlaceholder: "我想测试知识图谱和笔记流程……", demoRequestAgain: "再次申请", demoRequestButton: "申请权限", demoAwaitingReview: "等待审核", demoRequestSent: "演示权限申请已发送。", demoReviewQueue: "审核队列", demoAccessRequests: "演示权限申请", demoPendingCount: "待审核", demoApprovedCount: "已批准", demoTotalCount: "总计", demoNoMessage: "未填写留言。", demoReject: "拒绝", demoApprove: "批准", demoApproved: "内测权限已批准。", demoRejected: "内测权限申请已拒绝。", demoNoRequests: "暂无申请", demoNoRequestsText: "新的内测申请会自动显示在这里。"
};

const ja = {
  ...en,
  language: "言語", chooseLanguage: "言語を選択", chooseLanguageText: "ダッシュボードで使用する言語を選択します。",
  home: "ホーム", profile: "プロフィール", apiKeys: "APIキー", demo: "Webデモ", books: "書籍", users: "ユーザー", media: "メディア", admin: "システム運用", superadmin: "データベース", signOut: "ログアウト",
  dateLocale: "ja-JP", roleUser: "ユーザー", roleBetatester: "ベータテスター", roleManager: "マネージャー", roleStaff: "スタッフ", roleAdmin: "スタッフ", roleSuperadmin: "スタッフ", fileTypeFile: "ファイル", fileTypeFolder: "フォルダー",
  identity: "知識アイデンティティ", profileTitle: "プロフィール", profileText: "UMST アカウントに紐づく公開情報を更新します。", username: "ユーザー名", email: "メール", alias: "別名", description: "説明", saveProfile: "保存", saved: "プロフィールを保存しました。", authorityType: "アカウント種別", accountType: "アカウント種別",
  accountSecurity: "アカウントセキュリティ", changeEmail: "メールアドレスを変更", changeEmailText: "新しいアドレスへ送信された一回限りのリンクを確認するまで、現在のアドレスは有効です。現在のパスワードが必要で、確認後は既存セッションからログアウトします。", newEmail: "新しいメールアドレス", currentPassword: "現在のパスワード", sendEmailChange: "確認リンクを送信", emailChangeSent: "新しいアドレスに確認リンクを送信しました。確認するまで現在のメールは変更されません。",
  developer: "開発者アクセス", apiTitle: "APIキー", apiText: "通常キーは制限付き読み取りアクセスを提供します。対象となるスタッフアカウントは、自分のキーを取り込みとストレージ書き込み用の無制限マスターキーへ昇格できます。",
  keyName: "キー名", keyNameRequired: "キー名を入力してください。", createKey: "APIキーを作成", newKey: "新しいキー：", active: "有効", revoked: "無効", revoke: "無効化", regularKey: "通常キー", masterKey: "マスターキー", requestsPerHour: "リクエスト/時", unlimitedMaster: "無制限の読み取り、知識送信、埋め込み、ストレージ書き込み。", upgradeMaster: "マスターへ昇格", upgradeMasterConfirm: "このキーを無制限のマスターキーへ昇格しますか？ダッシュボードから元に戻せません。", masterUpgraded: "APIキーをマスターへ昇格しました。",
  adminTitle: "システム運用", adminText: "Qdrant の意味投影を検索し、オブジェクトストレージを管理します。データベースツールは別のワークスペースにあります。", vectorSearch: "意味検索", qdrantTitle: "Qdrant 検索", qdrantText: "埋め込みプロバイダー設定時はテキスト検索、またはベクトルを直接貼り付けできます。", queryText: "検索テキスト", queryTextPlaceholder: "これは何の例ですか？", queryVector: "検索ベクトル（任意）", filtersJson: "JSONペイロードフィルター", resultLimit: "結果数", searchQdrant: "Qdrantを検索", invalidJson: "JSONが無効です",
  files: "ファイル", objectStorage: "オブジェクトストレージ", storageText: "接続先 SERVER=", refresh: "更新", up: "上へ", newFolder: "新しいフォルダ名", createFolder: "フォルダ作成", newFile: "新しいテキスト", upload: "アップロード", download: "ダウンロード", delete: "削除", emptyFolder: "このフォルダは空です。", filePath: "ファイルパス", fileContent: "テキスト内容", saveFile: "保存", storageLoaded: "ストレージを読み込みました。", storageFileLoaded: "ファイルを読み込みました。", storagePathRequired: "ファイルパスを入力してください。", storageSaved: "保存しました。", folderNameRequired: "フォルダ名を入力してください。", folderCreated: "フォルダを作成しました。", fileUploaded: "アップロードしました。", deleteConfirm: "削除", deleted: "削除しました。", newFileReady: "パスと内容を入力して保存してください。",
  teamAccess: "チームアクセス", managerAccessTitle: "マネージャー権限", managerAccessText: "マネージャーは書籍カタログとニュースルームを管理できます。データベース、意味検索、オブジェクトストレージ、インフラストラクチャ機能にはアクセスできません。", usernameOrEmail: "ユーザー名またはメール", makeManager: "マネージャーにする", managerGranted: "さんをマネージャーに設定しました。",
  libraryOperations: "ライブラリ運営", booksTitle: "書籍", booksText: "構造化知識と AI 訓練エコシステムの情報源となる書籍カタログを管理します。", booksTracked: "冊を管理中", sectionsMapped: "セクションをマッピング済み", knowledgeObjects: "個の知識オブジェクト", newEntry: "新規登録", editing: "編集中", addBook: "書籍を追加", editBook: "書籍を編集", cancel: "キャンセル", bookTitle: "書名", bookTitlePlaceholder: "例：Linear Algebra Done Right", publisher: "出版社", isbn: "ISBN", publishDate: "出版日", version: "版", sourceKey: "ソースキー", saveChanges: "変更を保存", catalog: "カタログ", currentBooks: "登録済み書籍", unknownPublisher: "出版社未設定", dateNotSet: "日付未設定", sections: "セクション", objects: "オブジェクト", edit: "編集", noBooks: "書籍はまだありません", noBooksText: "フォームから最初の資料書籍を追加してください。", bookSaved: "書籍を保存しました。", bookDeleted: "書籍と関連コンテンツを削除しました。", deleteBookConfirm: "完全に削除", demoEnabled: "デモに表示", demoDisabled: "デモで非表示", enableDemo: "デモを有効化", disableDemo: "デモを無効化", enableDemoConfirm: "この書籍をWebデモに表示しますか", disableDemoConfirm: "この書籍をWebデモから外しますか", demoBookEnabled: "書籍をWebデモで有効にしました。", demoBookDisabled: "書籍をWebデモから外しました。",
  accountOperations: "アカウント運用", usersTitle: "ユーザー", usersText: "アカウント情報、アクセス状況、開発者キー、ベータ申請を確認します。", totalAccounts: "総アカウント数", pendingDemoRequests: "保留中のデモ申請", activeApiKeys: "有効なAPIキー", searchAccounts: "アカウント検索", searchAccountsPlaceholder: "ユーザー名、別名、メール", results: "件", account: "アカウント", demoAccess: "デモアクセス", lastSession: "最終セッション", joined: "登録日", never: "なし", notRequested: "未申請", usersLoading: "ユーザーを読み込み中…", noUsers: "ユーザーが見つかりません", noUsersText: "別の検索条件をお試しください。",
  editorialDesk: "編集デスク", mediaTitle: "メディア", mediaText: "ここで更新を公開すると、公開サイトに自動的に表示されます。", newStory: "新しい記事", editPost: "記事を編集", publishUpdate: "更新を公開", headline: "見出し", headlinePlaceholder: "コミュニティに何を伝えますか？", excerpt: "要約", excerptPlaceholder: "ニュースカード用の簡潔な紹介文。", story: "本文", storyPlaceholder: "更新の全文を入力…", imageUrl: "画像 URL", status: "ステータス", published: "公開済み", draft: "下書き", publishNow: "今すぐ公開", saveDraft: "下書きを保存", newsroom: "ニュースルーム", allPosts: "すべての記事", noPosts: "記事はまだありません", noPostsText: "フォームから最初の公開記事を作成してください。", postSaved: "記事を保存しました。公開済みの記事はサイトに反映されています。", postDeleted: "記事を削除しました。", deletePostConfirm: "削除",
  superadminTitle: "データベースツール", superadminText: "スタッフ権限を付与し、制御されたインフラストラクチャ操作を実行します。", userToPromote: "ユーザー", giveAdmin: "スタッフ権限を付与", adminGranted: "にスタッフ権限を付与しました。", superSql: "データベース管理", superSqlTitle: "直接PostgreSQL", superSqlText: "入力したPostgreSQLをそのまま実行し、明示的に許可されたスタッフのみ利用できます。", sqlCode: "SQLコード", runSql: "SQLを実行",
  demoProgram: "プライベートベータ", demoTitle: "学びの世界が形になり始めました。", demoText: "構造化された書籍をインタラクティブなグリモアとして探索し、生きた知識グラフを進み、UMST の学習・AI訓練エコシステムの基盤づくりに参加できます。", demoLoading: "デモ権限を確認中…", demoYourAccess: "アクセス権", demoReady: "グリモアが待っています", demoReadyText: "Webデモへのアクセスが許可されています。隔離された学習環境に入り、前回の続きから進めます。", demoPending: "審査中", demoPendingText: "チームが申請を確認します。承認後、入場ボタンが自動的に有効になります。", demoLocked: "プライベートベータ", demoLockedText: "最初の構造化学習体験へのアクセスを申請してください。", demoEnter: "Webデモへ入る", demoBetaAccess: "ベータアクセス", demoRequestReceived: "申請を受け付けました", demoRequestReceivedText: "申請は審査キューに安全に登録されています。", demoRequestTitle: "招待を申請", demoRequestText: "試したいことをチームに伝えてください。短いメッセージは任意です。", demoRequestMessage: "メッセージ", demoRequestPlaceholder: "知識グラフとノート機能を試したいです…", demoRequestAgain: "再申請", demoRequestButton: "アクセスを申請", demoAwaitingReview: "審査待ち", demoRequestSent: "デモアクセスを申請しました。", demoReviewQueue: "審査キュー", demoAccessRequests: "デモアクセス申請", demoPendingCount: "審査待ち", demoApprovedCount: "承認済み", demoTotalCount: "合計", demoNoMessage: "メッセージなし。", demoReject: "拒否", demoApprove: "承認", demoApproved: "ベータアクセスを承認しました。", demoRejected: "ベータアクセス申請を拒否しました。", demoNoRequests: "申請はありません", demoNoRequestsText: "新しいベータ申請は自動的にここへ表示されます。"
};

const text = { en, zh, ja };

export function useI18n() {
  const lang = ref(localStorage.getItem("language") || "en");
  const t = computed(() => text[lang.value] || text.en);
  function setLang(value) {
    if (!text[value]) return;
    lang.value = value;
    localStorage.setItem("language", value);
    document.documentElement.lang = htmlLang[value];
  }
  setLang(lang.value);
  return { lang, t, setLang };
}
