import { computed, ref } from "vue";

const DEFAULT_LANGUAGE = "en";

const htmlLang = {
  zh: "zh-CN",
  en: "en",
  ja: "ja"
};

export const languageOptions = [
  { code: "zh", labelKey: "language.zh" },
  { code: "en", labelKey: "language.en" },
  { code: "ja", labelKey: "language.ja" }
];

const text = {
  zh: {
    "brand.title": "UMST",
    "dashboard.title": "控制台",
    "language.label": "语言",
    "language.zh": "中文",
    "language.en": "English",
    "language.ja": "日本語",
    "nav.home": "首页",
    "nav.news": "新闻",
    "nav.about": "关于",
    "nav.wiki": "百科",
    "nav.login": "登录",
    "nav.get": "获取",
    "home.title": "探索、战斗、学习",
    "home.explore.title": "探索",
    "home.explore.text": "探索充满无限可能的世界，在变强的同时前往世界的深处与边界。",
    "home.learn.title": "学习",
    "home.learn.text": "通过革命性的节点式学习系统推进你的知识与学习，同时在游戏中不断前进。",
    "home.noDescription": "暂无简介。",
    "news.title": "UMST 新闻",
    "about.title": "关于 UMST",
    "wiki.title": "UMST 百科",
    "get.title": "获取 UMST",
    "login.title": "登录 UMST",
    "login.kicker": "进入知识图谱",
    "login.heading": "解锁你的知识。",
    "login.cardHeading": "欢迎回来",
    "login.username": "用户名",
    "login.password": "密码",
    "login.submit": "登录",
    "login.signup": "创建新账户",
    "login.badLogin": "用户名或密码不正确。",
    "login.note": "连接你的学习路径，继续探索定理、定义、世界与发现。",
    "signup.title": "注册 UMST",
    "signup.kicker": "开始新的知识旅程",
    "signup.heading": "建立你的知识宇宙。",
    "signup.cardHeading": "创建账户",
    "signup.username": "用户名",
    "signup.email": "邮箱",
    "signup.password": "密码",
    "signup.submit": "注册",
    "signup.login": "已有账户？登录",
    "signup.note": "创建账户，保存进度，扩展你的知识图谱。",
    "about.company.title": "关于 UMST",
    "about.company.text": "",
    "team.title": "领导团队",
    "team.field.bio": "简介",
    "team.field.focus": "职责重点",
    "team.chris.name": "Chris",
    "team.chris.role": "创始人 / CTO",
    "team.chris.bio": "剑桥大学学生，热爱数学、技术与音乐。",
    "team.chris.focus": "产品愿景、设计与部署。",
    "team.randall.name": "Randall",
    "team.randall.role": "战略顾问",
    "team.randall.bio": "擅长制定并执行全球战略，尤其关注中国及亚太市场增长，善于结合创新、本地能力与高绩效团队推动业务发展。作为东西方文化之间的桥梁，拥有工业设备、可再生能源、汽车等多个行业及职能领域经验。能够快速评估业务状况并识别机会，擅长应对高难度挑战并带领组织完成转型。兼具商业判断力与技术敏捷性，能够制定可在各层级落地的行动方案。致力于建设包容性团队文化、培养下一代领导者，并凝聚团队实现共同目标。",
    "team.randall.focus": "技术与战略分析、顾问支持与沟通。",
    "alt.logo": "UMST 标志",
    "alt.cave": "洞穴",
    "alt.graph": "图谱"
  },
  en: {
    "brand.title": "UMST",
    "dashboard.title": "Dashboard",
    "language.label": "Language",
    "language.zh": "中文",
    "language.en": "English",
    "language.ja": "日本語",
    "nav.home": "Home",
    "nav.news": "News",
    "nav.about": "About",
    "nav.wiki": "Wiki",
    "nav.login": "Login",
    "nav.get": "Get",
    "home.title": "Explore, Fight, Learn",
    "home.explore.title": "Explore",
    "home.explore.text": "Explore a space of endless possibility as you get stronger and venture to the depths and boundaries of the world.",
    "home.learn.title": "Learn",
    "home.learn.text": "Progress your knowledge and your studies with a revolutionary node-based learning system while you progress further in game.",
    "home.noDescription": "No description yet.",
    "news.title": "UMST News",
    "about.title": "About UMST",
    "wiki.title": "UMST Wiki",
    "get.title": "Get UMST",
    "login.title": "Log in to UMST",
    "login.kicker": "Enter the knowledge graph",
    "login.heading": "Unlock your knowledge.",
    "login.cardHeading": "Welcome back",
    "login.username": "Username",
    "login.password": "Password",
    "login.submit": "Log In",
    "login.signup": "Create a new account",
    "login.badLogin": "Incorrect username or password.",
    "login.note": "Reconnect with your learning path and keep exploring theorems, definitions, worlds, and discoveries.",
    "signup.title": "Sign up for UMST",
    "signup.kicker": "Start your knowledge journey",
    "signup.heading": "Build your knowledge universe.",
    "signup.cardHeading": "Create your account",
    "signup.username": "Username",
    "signup.email": "Email",
    "signup.password": "Password",
    "signup.submit": "Sign Up",
    "signup.login": "Already have an account? Log in",
    "signup.note": "Create an account to save progress and grow your personal knowledge graph.",
    "about.company.title": "About UMST",
    "about.company.text": "",
    "team.title": "Leadership Team",
    "team.field.bio": "Bio",
    "team.field.focus": "Focus",
    "team.chris.name": "Chris",
    "team.chris.role": "Founder / CTO",
    "team.chris.bio": "Student at the University of Cambridge, with strong interests in mathematics, technology, and music.",
    "team.chris.focus": "Product vision, design, and deployment.",
    "team.randall.name": "Randall",
    "team.randall.role": "Strategy Advisor",
    "team.randall.bio": "Experienced in developing and deploying global strategies, with a strong focus on China and APAC growth. He specializes in leveraging innovation, local capabilities, and high-performance teams. Serving as a cultural bridge between East and West, his background spans industrial equipment, renewable energy, automotive, and multiple business functions. He quickly assesses businesses, identifies opportunities, and is known for taking on difficult challenges while guiding organizations through change. He combines business acumen with technical agility to create practical plans across all levels of an organization. He is committed to inclusive work cultures, developing future leaders, and aligning teams around a shared vision of success.",
    "team.randall.focus": "Technical and strategic analysis, advisory support, and communication.",
    "alt.logo": "UMST logo",
    "alt.cave": "The Cave",
    "alt.graph": "The Graph"
  },
  ja: {
    "brand.title": "UMST",
    "dashboard.title": "ダッシュボード",
    "language.label": "言語",
    "language.zh": "中文",
    "language.en": "English",
    "language.ja": "日本語",
    "nav.home": "ホーム",
    "nav.news": "ニュース",
    "nav.about": "概要",
    "nav.wiki": "ウィキ",
    "nav.login": "ログイン",
    "nav.get": "入手",
    "home.title": "探索、戦闘、学習",
    "home.explore.title": "探索",
    "home.explore.text": "無限の可能性に満ちた世界を探索し、強くなりながら世界の深部と境界へ進んでいきます。",
    "home.learn.title": "学習",
    "home.learn.text": "革新的なノード型学習システムで知識と学習を進めながら、ゲーム内でもさらに前進します。",
    "home.noDescription": "説明はまだありません。",
    "news.title": "UMST ニュース",
    "about.title": "UMST について",
    "wiki.title": "UMST ウィキ",
    "get.title": "UMST を入手",
    "login.title": "UMST にログイン",
    "login.kicker": "知識グラフへ",
    "login.heading": "知識を解き放つ。",
    "login.cardHeading": "おかえりなさい",
    "login.username": "ユーザー名",
    "login.password": "パスワード",
    "login.submit": "ログイン",
    "login.signup": "新しいアカウントを作成",
    "login.badLogin": "ユーザー名またはパスワードが正しくありません。",
    "login.note": "学習の道筋に戻り、定理、定義、世界、発見をさらに探索しましょう。",
    "signup.title": "UMST に登録",
    "signup.kicker": "新しい知識の旅へ",
    "signup.heading": "知識の宇宙を築く。",
    "signup.cardHeading": "アカウント作成",
    "signup.username": "ユーザー名",
    "signup.email": "メール",
    "signup.password": "パスワード",
    "signup.submit": "登録",
    "signup.login": "すでにアカウントがありますか？ログイン",
    "signup.note": "アカウントを作成して進行状況を保存し、自分だけの知識グラフを広げましょう。",
    "about.company.title": "UMST について",
    "about.company.text": "",
    "team.title": "リーダーシップチーム",
    "team.field.bio": "プロフィール",
    "team.field.focus": "担当領域",
    "team.chris.name": "Chris",
    "team.chris.role": "創設者 / CTO",
    "team.chris.bio": "ケンブリッジ大学の学生。数学、テクノロジー、音楽に強い関心を持つ。",
    "team.chris.focus": "プロダクトビジョン、設計、デプロイメント。",
    "team.randall.name": "Randall",
    "team.randall.role": "戦略アドバイザー",
    "team.randall.bio": "中国およびAPAC地域での成長を重視したグローバル戦略の策定と実行に豊富な経験を持つ。イノベーション、現地の能力、高い成果を出すチームを活用して事業成長を推進する。東西文化の橋渡し役として、産業機器、再生可能エネルギー、自動車など複数の業界と職能領域にわたる経験を有する。事業を素早く評価し、機会を見出し、困難な課題に取り組みながら組織変革を導くことで知られている。優れたビジネス判断力と技術的な柔軟性を兼ね備え、組織の各階層で実行可能な計画を作成できる。包摂的な職場文化の構築、次世代リーダーの育成、共通の成功ビジョンに向けたチームの結集に尽力している。",
    "team.randall.focus": "技術・戦略分析、アドバイザリー、コミュニケーション。",
    "alt.logo": "UMST ロゴ",
    "alt.cave": "洞窟",
    "alt.graph": "グラフ"
  }
};

export function useWebI18n() {
  const lang = ref(localStorage.getItem("language") || DEFAULT_LANGUAGE);
  const currentText = computed(() => text[lang.value] || text[DEFAULT_LANGUAGE]);

  function setLang(value) {
    lang.value = text[value] ? value : DEFAULT_LANGUAGE;
    localStorage.setItem("language", lang.value);
    document.documentElement.lang = htmlLang[lang.value];
  }

  function tr(key) {
    return currentText.value[key] || text[DEFAULT_LANGUAGE][key] || "";
  }

  setLang(lang.value);
  return { lang, tr, setLang, languageOptions };
}
