import { computed, ref } from "vue";

const DEFAULT_LANGUAGE = "en";

const htmlLang = {
  zh: "zh-CN",
  en: "en",
  ja: "ja"
};

export const languageOptions = [
  { code: "zh", labelKey: "language.zh" },
  { code: "en", labelKey: "language.en" },
  { code: "ja", labelKey: "language.ja" }
];

const text = {
  zh: {
    "brand.title": "theumst",
    "brand.category": "知识基础设施",
    "locale.code": "zh-CN",
    "dashboard.title": "控制台",
    "language.label": "语言",
    "language.zh": "中文",
    "language.en": "English",
    "language.ja": "日本語",
    "nav.home": "首页",
    "nav.news": "新闻",
    "nav.about": "关于",
    "nav.wiki": "百科",
    "nav.demo": "演示",
    "nav.login": "登录",
    "nav.get": "加入",
    "home.title": "探索知识，训练智能",
    "home.explore.title": "探索",
    "home.explore.text": "探索充满无限可能的世界，在变强的同时前往世界的深处与边界。",
    "home.learn.title": "学习",
    "home.learn.text": "通过革命性的节点式学习系统推进你的知识与学习，同时在游戏中不断前进。",
    "home.noDescription": "暂无简介。",
    "home.welcomeBack": "欢迎回来",
    "home.kicker": "基于人类知识构建的世界",
    "home.heading": "探索知识，训练智能。",
    "home.lead": "theumst 将教材、论文与专家洞见转化为一个结构化世界，用于学习、评估与更安全的人工智能开发。",
    "home.cta.primary": "加入生态系统",
    "home.cta.secondary": "了解愿景",
    "home.trust.structured": "从源头实现结构化",
    "home.trust.reviewed": "人工与 AI 共同审核",
    "home.trust.measurable": "进步可衡量",
    "home.world.status": "世界状态",
    "home.world.title": "知识前沿",
    "home.world.objective": "当前目标",
    "home.world.quest": "绘制隐藏定理的图谱",
    "home.world.node1": "几何学已解锁",
    "home.world.node2": "已找到证明路径",
    "home.signal.source": "教材与论文",
    "home.signal.structure": "结构化提取",
    "home.signal.experience": "学习世界",
    "home.signal.training": "训练与评估",
    "home.ecosystem.kicker": "一体化生态系统",
    "home.ecosystem.heading": "知识既能被探索，也能被智能系统学习。",
    "home.ecosystem.lead": "同一套有据可查的数据层，既可支持当下引人入胜的学习体验，也能逐步发展为更丰富的基准测试与 AI 安全生态系统。",
    "home.ecosystem.game.title": "由知识驱动的世界",
    "home.ecosystem.game.text": "玩家通过理解思想、连接概念和运用知识来推进进度，而不是死记孤立的答案。",
    "home.ecosystem.game.tag": "交互式学习愿景",
    "home.ecosystem.data.title": "结构化训练数据",
    "home.ecosystem.data.text": "教材与论文被转化为可追溯的知识对象，其中包含语境、关系、证据和可衡量的结果。",
    "home.ecosystem.data.tag": "以可靠依据为设计核心",
    "home.ecosystem.safety.title": "面向更安全 AI 的基准测试",
    "home.ecosystem.safety.text": "知识图谱可支持透明评估、揭示模型弱点，并为对齐研究提供经专家审核的信号。",
    "home.ecosystem.safety.tag": "长期前沿",
    "home.graph.caption": "互联的知识对象",
    "home.graph.live": "持续演化的图谱",
    "home.graph.kicker": "信任融入系统架构",
    "home.graph.heading": "AI 扩展工作规模，专家守护信息质量。",
    "home.graph.text": "长期审核系统将机器的速度与人类的判断结合起来，生成实用、可检查并能持续改进的数据。",
    "home.graph.step1.title": "提取并连接",
    "home.graph.step1.text": "AI 将源材料整理为概念、论断、关系和证据。",
    "home.graph.step2.title": "衡量并挑战",
    "home.graph.step2.text": "模型与学习者完成可检查来源和结果的任务。",
    "home.graph.step3.title": "审核并改进",
    "home.graph.step3.text": "AI 审核员标记问题；人类专家裁决困难或影响重大的材料。",
    "home.news.kicker": "来自新闻中心",
    "home.news.heading": "公开记录建设进展",
    "home.news.all": "查看全部动态",
    "home.news.coming": "即将发布",
    "home.news.emptyTitle": "首篇动态正在准备中。",
    "home.news.emptyText": "编辑团队发布的新闻会自动显示在这里。",
    "home.final.kicker": "前沿已经开放",
    "home.final.heading": "共同打造更好的学习方式，以及更好的智能评估方式。",
    "home.final.cta": "创建账户",
    "footer.line": "交互式学习与可信智能。",
    "footer.privacy": "隐私",
    "privacy.title": "隐私政策",
    "news.title": "theumst 新闻",
    "news.intro": "来自 theumst 团队的产品思考、研究笔记与重要进展。",
    "news.updates": "篇动态",
    "news.published": "已发布",
    "news.empty.title": "暂时没有公开动态。",
    "news.empty.text": "通过媒体控制台发布的内容会自动显示在这里。",
    "about.title": "关于 theumst",
    "wiki.title": "theumst 百科",
    "get.title": "加入 theumst",
    "login.title": "登录 UMST",
    "login.kicker": "进入知识图谱",
    "login.heading": "解锁你的知识。",
    "login.cardHeading": "欢迎回来",
    "login.username": "用户名",
    "login.password": "密码",
    "login.submit": "登录",
    "login.signup": "创建新账户",
    "login.forgot": "忘记密码？",
    "login.badLogin": "用户名或密码不正确。",
    "login.resetSuccess": "密码已更新。请使用新密码登录。",
    "login.verifiedSuccess": "邮箱已确认。你现在可以登录。",
    "login.resendVerification": "重新发送确认邮件",
    "login.note": "连接你的学习路径，继续探索定理、定义、世界与发现。",
    "forgot.title": "找回密码",
    "forgot.kicker": "账户安全",
    "forgot.heading": "重新进入你的知识世界。",
    "forgot.cardHeading": "发送重置链接",
    "forgot.note": "输入账户邮箱，我们会发送一次性安全链接。",
    "forgot.email": "邮箱",
    "forgot.submit": "发送重置链接",
    "forgot.sending": "正在发送…",
    "forgot.back": "返回登录",
    "reset.title": "重置密码",
    "reset.kicker": "安全恢复",
    "reset.heading": "设置新密码。",
    "reset.cardHeading": "保护你的账户",
    "reset.note": "重置链接只能使用一次，完成后现有会话将退出。",
    "reset.password": "新密码",
    "reset.confirm": "确认新密码",
    "reset.submit": "更新密码",
    "reset.sending": "正在更新…",
    "reset.back": "返回登录",
    "reset.mismatch": "两次输入的密码不一致。",
    "reset.invalid": "此重置链接无效或已过期。",
    "reset.success": "密码已更新。现在可以登录。",
    "signup.title": "注册 UMST",
    "signup.kicker": "开始新的知识旅程",
    "signup.heading": "建立你的知识宇宙。",
    "signup.cardHeading": "创建账户",
    "signup.username": "用户名",
    "signup.email": "邮箱",
    "signup.password": "密码",
    "signup.submit": "注册",
    "signup.login": "已有账户？登录",
    "signup.note": "创建账户，保存进度，扩展你的知识图谱。",
    "signup.verifyNote": "我们会向你的邮箱发送确认链接；确认后才能登录。",
    "verify.title": "确认邮箱",
    "verify.kicker": "账户安全",
    "verify.heading": "确认这是你的邮箱。",
    "verify.cardHeading": "邮箱确认",
    "verify.note": "确认邮箱可以保护账户，并确保我们能在需要时联系到你。",
    "verify.checking": "正在确认链接…",
    "verify.success": "邮箱已确认。你的账户现在可以使用。",
    "verify.sent": "如果该地址对应尚未确认的账户，新的确认链接已发送。请检查收件箱。",
    "verify.failed": "无法使用此确认链接。它可能已过期。",
    "verify.instructions": "输入注册时使用的邮箱，我们将发送新的确认链接。",
    "verify.resend": "重新发送确认邮件",
    "verify.login": "前往登录",
    "about.company.title": "关于 UMST",
    "about.company.text": "theumst 是一个研究与教育平台，围绕一个简单理念而构建：知识应当可以探索、可以衡量，并能同时服务于人类和智能系统。我们正在为交互式学习世界、结构化 AI 训练数据、专家审核以及更丰富的基准测试生态系统奠定基础，从而为 AI 安全作出贡献。",
    "wiki.intro": "公共知识库正在建设中。它将让有据可查的概念、关系与来源脉络更容易被探索。",
    "get.intro": "theumst 正在积极开发中。创建账户，加入这个从结构化知识走向交互式学习的生态系统。",
    "team.title": "领导团队",
    "team.field.bio": "简介",
    "team.field.focus": "职责重点",
    "team.chris.name": "Chris",
    "team.chris.role": "创始人 / CTO",
    "team.chris.bio": "剑桥大学学生，热爱数学、技术与音乐。",
    "team.chris.focus": "产品愿景、设计与部署。",
    "team.randall.name": "Randall",
    "team.randall.role": "战略顾问",
    "team.randall.bio": "擅长制定并执行全球战略，尤其关注中国及亚太市场增长，善于结合创新、本地能力与高绩效团队推动业务发展。作为东西方文化之间的桥梁，拥有工业设备、可再生能源、汽车等多个行业及职能领域经验。能够快速评估业务状况并识别机会，擅长应对高难度挑战并带领组织完成转型。兼具商业判断力与技术敏捷性，能够制定可在各层级落地的行动方案。致力于建设包容性团队文化、培养下一代领导者，并凝聚团队实现共同目标。",
    "team.randall.focus": "技术与战略分析、顾问支持与沟通。",
    "team.tina.name": "Tina",
    "team.tina.role": "社交媒体顾问",
    "team.tina.bio": "纽约大学学生，纽约大学坦登工程学院中国学生学者联合会外联负责人，热爱音乐。",
    "team.tina.focus": "沟通策略、社交媒体活动与内容流程。",
    "alt.logo": "UMST 标志",
    "alt.cave": "洞穴",
    "alt.graph": "图谱",
    "alt.world": "theumst 学习世界概念图"
  },
  en: {
    "brand.title": "theumst",
    "brand.category": "Knowledge infrastructure",
    "locale.code": "en-GB",
    "dashboard.title": "Dashboard",
    "language.label": "Language",
    "language.zh": "中文",
    "language.en": "English",
    "language.ja": "日本語",
    "nav.home": "Home",
    "nav.news": "News",
    "nav.about": "About",
    "nav.wiki": "Wiki",
    "nav.demo": "Demo",
    "nav.login": "Login",
    "nav.get": "Join",
    "home.title": "Explore knowledge. Train intelligence.",
    "home.explore.title": "Explore",
    "home.explore.text": "Explore a space of endless possibility as you get stronger and venture to the depths and boundaries of the world.",
    "home.learn.title": "Learn",
    "home.learn.text": "Progress your knowledge and your studies with a revolutionary node-based learning system while you progress further in game.",
    "home.noDescription": "No description yet.",
    "home.welcomeBack": "Welcome back",
    "home.kicker": "A world built from what humanity knows",
    "home.heading": "Explore knowledge. Train intelligence.",
    "home.lead": "theumst transforms textbooks, papers, and expert insight into a structured world for learning, evaluation, and safer AI development.",
    "home.cta.primary": "Join the ecosystem",
    "home.cta.secondary": "See the vision",
    "home.trust.structured": "Structured at source",
    "home.trust.reviewed": "Human + AI reviewed",
    "home.trust.measurable": "Measurable progress",
    "home.world.status": "World status",
    "home.world.title": "Knowledge frontier",
    "home.world.objective": "Current objective",
    "home.world.quest": "Map the hidden theorem",
    "home.world.node1": "Geometry unlocked",
    "home.world.node2": "Proof path found",
    "home.signal.source": "Books and papers",
    "home.signal.structure": "Structured extraction",
    "home.signal.experience": "Learning world",
    "home.signal.training": "Training and evaluation",
    "home.ecosystem.kicker": "One connected ecosystem",
    "home.ecosystem.heading": "Knowledge becomes something you can explore—and something intelligence can learn from.",
    "home.ecosystem.lead": "The same grounded data layer can support an engaging learning experience today and a richer benchmarking and AI-safety ecosystem over time.",
    "home.ecosystem.game.title": "A knowledge-driven world",
    "home.ecosystem.game.text": "Players progress by understanding ideas, connecting concepts, and applying knowledge—not by memorising isolated answers.",
    "home.ecosystem.game.tag": "Interactive learning vision",
    "home.ecosystem.data.title": "Structured training data",
    "home.ecosystem.data.text": "Books and papers become traceable knowledge objects with context, relationships, evidence, and measurable outcomes.",
    "home.ecosystem.data.tag": "Grounded by design",
    "home.ecosystem.safety.title": "Benchmarks for safer AI",
    "home.ecosystem.safety.text": "The graph can support transparent evaluations, reveal model weaknesses, and create expert-reviewed signals for alignment research.",
    "home.ecosystem.safety.tag": "Long-term frontier",
    "home.graph.caption": "Connected knowledge objects",
    "home.graph.live": "Living graph",
    "home.graph.kicker": "Trust is part of the architecture",
    "home.graph.heading": "AI scales the work. Experts protect the signal.",
    "home.graph.text": "The long-term review system combines machine speed with human judgment, creating data that is useful, inspectable, and continuously improved.",
    "home.graph.step1.title": "Extract and connect",
    "home.graph.step1.text": "AI structures source material into concepts, claims, relationships, and evidence.",
    "home.graph.step2.title": "Measure and challenge",
    "home.graph.step2.text": "Models and learners engage with tasks whose provenance and outcomes can be inspected.",
    "home.graph.step3.title": "Review and improve",
    "home.graph.step3.text": "AI reviewers flag issues; human experts adjudicate difficult or high-impact material.",
    "home.news.kicker": "From the newsroom",
    "home.news.heading": "Building in public",
    "home.news.all": "View all updates",
    "home.news.coming": "Coming soon",
    "home.news.emptyTitle": "The first update is being prepared.",
    "home.news.emptyText": "News published by the editorial team will appear here automatically.",
    "home.final.kicker": "The frontier is open",
    "home.final.heading": "Help build a better way to learn—and a better way to evaluate intelligence.",
    "home.final.cta": "Create an account",
    "footer.line": "Interactive learning and trusted intelligence.",
    "footer.privacy": "Privacy",
    "privacy.title": "Privacy policy",
    "news.title": "News from theumst",
    "news.intro": "Product thinking, research notes, and milestones from the team building theumst.",
    "news.updates": "updates",
    "news.published": "Published",
    "news.empty.title": "No public updates yet.",
    "news.empty.text": "Published stories from the media dashboard will appear here automatically.",
    "about.title": "About theumst",
    "wiki.title": "UMST Wiki",
    "get.title": "Join theumst",
    "login.title": "Log in to UMST",
    "login.kicker": "Enter the knowledge graph",
    "login.heading": "Unlock your knowledge.",
    "login.cardHeading": "Welcome back",
    "login.username": "Username",
    "login.password": "Password",
    "login.submit": "Log In",
    "login.signup": "Create a new account",
    "login.forgot": "Forgot your password?",
    "login.badLogin": "Incorrect username or password.",
    "login.resetSuccess": "Your password has been updated. Log in with your new password.",
    "login.verifiedSuccess": "Your email is confirmed. You can now log in.",
    "login.resendVerification": "Resend confirmation email",
    "login.note": "Reconnect with your learning path and keep exploring theorems, definitions, worlds, and discoveries.",
    "forgot.title": "Recover your password",
    "forgot.kicker": "Account security",
    "forgot.heading": "Find your way back in.",
    "forgot.cardHeading": "Send a reset link",
    "forgot.note": "Enter the email address on your account. We will send a secure, one-use link if it matches.",
    "forgot.email": "Email address",
    "forgot.submit": "Send reset link",
    "forgot.sending": "Sending…",
    "forgot.back": "Back to login",
    "reset.title": "Reset your password",
    "reset.kicker": "Secure recovery",
    "reset.heading": "Choose a new password.",
    "reset.cardHeading": "Secure your account",
    "reset.note": "Your link works once. Completing the reset signs out existing sessions for your protection.",
    "reset.password": "New password",
    "reset.confirm": "Confirm new password",
    "reset.submit": "Update password",
    "reset.sending": "Updating…",
    "reset.back": "Back to login",
    "reset.mismatch": "The passwords do not match.",
    "reset.invalid": "This reset link is invalid or has expired.",
    "reset.success": "Your password has been updated. You can now log in.",
    "signup.title": "Sign up for UMST",
    "signup.kicker": "Start your knowledge journey",
    "signup.heading": "Build your knowledge universe.",
    "signup.cardHeading": "Create your account",
    "signup.username": "Username",
    "signup.email": "Email",
    "signup.password": "Password",
    "signup.submit": "Sign Up",
    "signup.login": "Already have an account? Log in",
    "signup.note": "Create an account to save progress and grow your personal knowledge graph.",
    "signup.verifyNote": "We will email you a confirmation link. You must confirm it before you can log in.",
    "verify.title": "Confirm your email",
    "verify.kicker": "Account security",
    "verify.heading": "Confirm it is really you.",
    "verify.cardHeading": "Email confirmation",
    "verify.note": "Confirming your address protects your account and ensures we can reach you when needed.",
    "verify.checking": "Checking your confirmation link…",
    "verify.success": "Your email is confirmed and your account is ready to use.",
    "verify.sent": "If an unconfirmed account matches that address, a new link has been sent. Check your inbox.",
    "verify.failed": "This confirmation link could not be used. It may have expired.",
    "verify.instructions": "Enter the email address used to sign up and we will send a new confirmation link.",
    "verify.resend": "Resend confirmation email",
    "verify.login": "Continue to login",
    "about.company.title": "About UMST",
    "about.company.text": "theumst is a research and education platform built around a simple idea: knowledge should be explorable, measurable, and useful to both people and intelligent systems. We are building the foundations for an interactive learning world, structured AI training data, expert review, and a richer benchmarking ecosystem that can contribute to AI safety.",
    "wiki.intro": "The public knowledge library is being prepared. It will make grounded concepts, relationships, and source provenance easier to explore.",
    "get.intro": "theumst is in active development. Create an account to join the ecosystem and follow the journey from structured knowledge to interactive learning.",
    "team.title": "Leadership Team",
    "team.field.bio": "Bio",
    "team.field.focus": "Focus",
    "team.chris.name": "Chris",
    "team.chris.role": "Founder / CTO",
    "team.chris.bio": "Student at the University of Cambridge, with strong interests in mathematics, technology, and music.",
    "team.chris.focus": "Product vision, design, and deployment.",
    "team.randall.name": "Randall",
    "team.randall.role": "Strategy Advisor",
    "team.randall.bio": "Experienced in developing and deploying global strategies, with a strong focus on China and APAC growth. He specializes in leveraging innovation, local capabilities, and high-performance teams. Serving as a cultural bridge between East and West, his background spans industrial equipment, renewable energy, automotive, and multiple business functions. He quickly assesses businesses, identifies opportunities, and is known for taking on difficult challenges while guiding organizations through change. He combines business acumen with technical agility to create practical plans across all levels of an organization. He is committed to inclusive work cultures, developing future leaders, and aligning teams around a shared vision of success.",
    "team.randall.focus": "Technical and strategic analysis, advisory support, and communication.",
    "team.tina.name": "Tina",
    "team.tina.role": "Social Media Advisor",
    "team.tina.bio": "Student at NYU, External Affairs Coordinator for NYU Tandon CSSA, and music enthusiast.",
    "team.tina.focus": "Communication strategy, social media activity, and content pipelines.",
    "alt.logo": "UMST logo",
    "alt.cave": "The Cave",
    "alt.graph": "The Graph",
    "alt.world": "Concept art of the theumst learning world"
  },
  ja: {
    "brand.title": "theumst",
    "brand.category": "知識インフラ",
    "locale.code": "ja-JP",
    "dashboard.title": "ダッシュボード",
    "language.label": "言語",
    "language.zh": "中文",
    "language.en": "English",
    "language.ja": "日本語",
    "nav.home": "ホーム",
    "nav.news": "ニュース",
    "nav.about": "概要",
    "nav.wiki": "ウィキ",
    "nav.demo": "デモ",
    "nav.login": "ログイン",
    "nav.get": "参加する",
    "home.title": "知識を探索し、知能を育てる",
    "home.explore.title": "探索",
    "home.explore.text": "無限の可能性に満ちた世界を探索し、強くなりながら世界の深部と境界へ進んでいきます。",
    "home.learn.title": "学習",
    "home.learn.text": "革新的なノード型学習システムで知識と学習を進めながら、ゲーム内でもさらに前進します。",
    "home.noDescription": "説明はまだありません。",
    "home.welcomeBack": "おかえりなさい",
    "home.kicker": "人類の知識から構築された世界",
    "home.heading": "知識を探索し、知能を育てる。",
    "home.lead": "theumst は、教科書、論文、専門家の知見を、学習・評価・より安全な AI 開発のための構造化された世界へ変換します。",
    "home.cta.primary": "エコシステムに参加",
    "home.cta.secondary": "ビジョンを見る",
    "home.trust.structured": "情報源から構造化",
    "home.trust.reviewed": "人間と AI によるレビュー",
    "home.trust.measurable": "測定可能な進歩",
    "home.world.status": "ワールド状況",
    "home.world.title": "知識の最前線",
    "home.world.objective": "現在の目標",
    "home.world.quest": "隠された定理をマッピング",
    "home.world.node1": "幾何学を解除",
    "home.world.node2": "証明経路を発見",
    "home.signal.source": "教科書と論文",
    "home.signal.structure": "構造化抽出",
    "home.signal.experience": "学習世界",
    "home.signal.training": "訓練と評価",
    "home.ecosystem.kicker": "一つにつながるエコシステム",
    "home.ecosystem.heading": "知識は探索できるものに、そして知能が学べるものになる。",
    "home.ecosystem.lead": "同じ根拠あるデータ基盤が、現在の魅力的な学習体験を支え、将来はより豊かなベンチマークと AI セーフティのエコシステムへ発展します。",
    "home.ecosystem.game.title": "知識が動かす世界",
    "home.ecosystem.game.text": "プレイヤーは孤立した答えを暗記するのではなく、考えを理解し、概念をつなぎ、知識を応用することで進みます。",
    "home.ecosystem.game.tag": "インタラクティブ学習のビジョン",
    "home.ecosystem.data.title": "構造化された訓練データ",
    "home.ecosystem.data.text": "教科書と論文は、文脈、関係、根拠、測定可能な成果を備えた追跡可能な知識オブジェクトになります。",
    "home.ecosystem.data.tag": "根拠を中心とした設計",
    "home.ecosystem.safety.title": "より安全な AI のためのベンチマーク",
    "home.ecosystem.safety.text": "知識グラフは透明な評価を支え、モデルの弱点を明らかにし、アラインメント研究に専門家レビュー済みのシグナルを提供できます。",
    "home.ecosystem.safety.tag": "長期的なフロンティア",
    "home.graph.caption": "つながった知識オブジェクト",
    "home.graph.live": "進化し続けるグラフ",
    "home.graph.kicker": "信頼をアーキテクチャに組み込む",
    "home.graph.heading": "AI が作業を拡張し、専門家が情報の質を守る。",
    "home.graph.text": "長期的なレビューシステムは、機械の速度と人間の判断を組み合わせ、実用的で検証可能、かつ継続的に改善されるデータを生み出します。",
    "home.graph.step1.title": "抽出してつなぐ",
    "home.graph.step1.text": "AI が情報源を概念、主張、関係、根拠として構造化します。",
    "home.graph.step2.title": "測定して挑む",
    "home.graph.step2.text": "モデルと学習者は、出典と結果を検証できる課題に取り組みます。",
    "home.graph.step3.title": "レビューして改善する",
    "home.graph.step3.text": "AI レビュアーが問題を検出し、人間の専門家が難しい内容や影響の大きい内容を判断します。",
    "home.news.kicker": "ニュースルームから",
    "home.news.heading": "開発の歩みを公開",
    "home.news.all": "すべての更新を見る",
    "home.news.coming": "近日公開",
    "home.news.emptyTitle": "最初の更新を準備しています。",
    "home.news.emptyText": "編集チームが公開したニュースは、ここに自動的に表示されます。",
    "home.final.kicker": "フロンティアは開かれている",
    "home.final.heading": "より良い学び方と、より良い知能の評価方法を共につくりましょう。",
    "home.final.cta": "アカウントを作成",
    "footer.line": "インタラクティブな学習と信頼できる知能。",
    "footer.privacy": "プライバシー",
    "privacy.title": "プライバシーポリシー",
    "news.title": "theumst ニュース",
    "news.intro": "theumst を構築するチームからのプロダクトの考察、研究ノート、マイルストーン。",
    "news.updates": "件の更新",
    "news.published": "公開済み",
    "news.empty.title": "公開された更新はまだありません。",
    "news.empty.text": "メディアダッシュボードで公開した記事は、ここに自動的に表示されます。",
    "about.title": "theumst について",
    "wiki.title": "theumst ウィキ",
    "get.title": "theumst に参加",
    "login.title": "UMST にログイン",
    "login.kicker": "知識グラフへ",
    "login.heading": "知識を解き放つ。",
    "login.cardHeading": "おかえりなさい",
    "login.username": "ユーザー名",
    "login.password": "パスワード",
    "login.submit": "ログイン",
    "login.signup": "新しいアカウントを作成",
    "login.forgot": "パスワードをお忘れですか？",
    "login.badLogin": "ユーザー名またはパスワードが正しくありません。",
    "login.resetSuccess": "パスワードを更新しました。新しいパスワードでログインしてください。",
    "login.verifiedSuccess": "メールを確認しました。ログインできます。",
    "login.resendVerification": "確認メールを再送",
    "login.note": "学習の道筋に戻り、定理、定義、世界、発見をさらに探索しましょう。",
    "forgot.title": "パスワードを復旧",
    "forgot.kicker": "アカウントセキュリティ",
    "forgot.heading": "知識の世界へ戻りましょう。",
    "forgot.cardHeading": "リセットリンクを送信",
    "forgot.note": "アカウントのメールアドレスを入力してください。一致する場合、安全な一回限りのリンクを送信します。",
    "forgot.email": "メールアドレス",
    "forgot.submit": "リセットリンクを送信",
    "forgot.sending": "送信中…",
    "forgot.back": "ログインに戻る",
    "reset.title": "パスワードをリセット",
    "reset.kicker": "安全な復旧",
    "reset.heading": "新しいパスワードを設定。",
    "reset.cardHeading": "アカウントを保護",
    "reset.note": "リンクは一度だけ使用でき、完了すると既存のセッションはログアウトされます。",
    "reset.password": "新しいパスワード",
    "reset.confirm": "新しいパスワードを確認",
    "reset.submit": "パスワードを更新",
    "reset.sending": "更新中…",
    "reset.back": "ログインに戻る",
    "reset.mismatch": "パスワードが一致しません。",
    "reset.invalid": "このリセットリンクは無効か、有効期限が切れています。",
    "reset.success": "パスワードを更新しました。ログインできます。",
    "signup.title": "UMST に登録",
    "signup.kicker": "新しい知識の旅へ",
    "signup.heading": "知識の宇宙を築く。",
    "signup.cardHeading": "アカウント作成",
    "signup.username": "ユーザー名",
    "signup.email": "メール",
    "signup.password": "パスワード",
    "signup.submit": "登録",
    "signup.login": "すでにアカウントがありますか？ログイン",
    "signup.note": "アカウントを作成して進行状況を保存し、自分だけの知識グラフを広げましょう。",
    "signup.verifyNote": "確認リンクをメールで送信します。ログインする前に確認してください。",
    "verify.title": "メールを確認",
    "verify.kicker": "アカウントセキュリティ",
    "verify.heading": "メールアドレスを確認してください。",
    "verify.cardHeading": "メール確認",
    "verify.note": "メール確認によりアカウントを保護し、必要な連絡を確実に受け取れます。",
    "verify.checking": "確認リンクを検証中…",
    "verify.success": "メールを確認しました。アカウントを利用できます。",
    "verify.sent": "未確認のアカウントが一致する場合、新しいリンクを送信しました。受信箱をご確認ください。",
    "verify.failed": "この確認リンクは使用できません。有効期限が切れている可能性があります。",
    "verify.instructions": "登録時のメールアドレスを入力すると、新しい確認リンクを送信します。",
    "verify.resend": "確認メールを再送",
    "verify.login": "ログインへ進む",
    "about.company.title": "UMST について",
    "about.company.text": "theumst は、知識は探索でき、測定でき、人と知能システムの双方に役立つべきだというシンプルな考えに基づく研究・教育プラットフォームです。インタラクティブな学習世界、構造化された AI 訓練データ、専門家レビュー、そして AI セーフティに貢献できるより豊かなベンチマーク・エコシステムの基盤を築いています。",
    "wiki.intro": "公開知識ライブラリを準備しています。根拠ある概念、関係、情報源の来歴を、より簡単に探索できるようになります。",
    "get.intro": "theumst は現在活発に開発中です。アカウントを作成してエコシステムに参加し、構造化された知識からインタラクティブな学習へ進む歩みを追いましょう。",
    "team.title": "リーダーシップチーム",
    "team.field.bio": "プロフィール",
    "team.field.focus": "担当領域",
    "team.chris.name": "Chris",
    "team.chris.role": "創設者 / CTO",
    "team.chris.bio": "ケンブリッジ大学の学生。数学、テクノロジー、音楽に強い関心を持つ。",
    "team.chris.focus": "プロダクトビジョン、設計、デプロイメント。",
    "team.randall.name": "Randall",
    "team.randall.role": "戦略アドバイザー",
    "team.randall.bio": "中国およびAPAC地域での成長を重視したグローバル戦略の策定と実行に豊富な経験を持つ。イノベーション、現地の能力、高い成果を出すチームを活用して事業成長を推進する。東西文化の橋渡し役として、産業機器、再生可能エネルギー、自動車など複数の業界と職能領域にわたる経験を有する。事業を素早く評価し、機会を見出し、困難な課題に取り組みながら組織変革を導くことで知られている。優れたビジネス判断力と技術的な柔軟性を兼ね備え、組織の各階層で実行可能な計画を作成できる。包摂的な職場文化の構築、次世代リーダーの育成、共通の成功ビジョンに向けたチームの結集に尽力している。",
    "team.randall.focus": "技術・戦略分析、アドバイザリー、コミュニケーション。",
    "team.tina.name": "Tina",
    "team.tina.role": "ソーシャルメディア・アドバイザー",
    "team.tina.bio": "ニューヨーク大学の学生。NYU Tandon CSSAの渉外担当コーディネーターであり、音楽を愛好している。",
    "team.tina.focus": "コミュニケーション戦略、ソーシャルメディア活動、コンテンツ運用フロー。",
    "alt.logo": "UMST ロゴ",
    "alt.cave": "洞窟",
    "alt.graph": "グラフ",
    "alt.world": "theumst 学習世界のコンセプトアート"
  }
};

export function useWebI18n() {
  const lang = ref(localStorage.getItem("language") || DEFAULT_LANGUAGE);
  const currentText = computed(() => text[lang.value] || text[DEFAULT_LANGUAGE]);

  function setLang(value) {
    lang.value = text[value] ? value : DEFAULT_LANGUAGE;
    localStorage.setItem("language", lang.value);
    document.documentElement.lang = htmlLang[lang.value];
  }

  function tr(key) {
    return currentText.value[key] || text[DEFAULT_LANGUAGE][key] || "";
  }

  setLang(lang.value);
  return { lang, tr, setLang, languageOptions };
}
