const en = {
  close: "Close",
  expand: "Expand",
  restore: "Restore",
  sceneNavigation: "Scene navigation",
  environment: "Library and cave environment",
  home: "Home",
  about: "About",
  news: "News",
  wiki: "Wiki",
  demo: "Demo",
  get: "Join",
  login: "Login",
  settings: "Settings",
  profile: "Profile",
  yourProfile: "Your profile",
  dashboard: "Dashboard",
  card: "Member card",
  pages: "Website pages",
  previous: "Previous pages",
  more: "More pages",
  details: "Details",
  subscriptions: "Subscriptions",
  viewCard: "View card",
  openDashboard: "Open dashboard",
  finish: "Finish",
  downloadCard: "Download card",
  save: "Save preferences",
  newsTitle: "A note now and then.",
  newsIntro: "Choose what reaches your inbox.",
  newsChoice: "Theumst news",
  newsDescription: "New announcements from the News page.",
  subscribe: "Email me Theumst news",
  optional: "Optional. You can unsubscribe at any time.",
  footnote:
    "You can unsubscribe here or from any announcement. Account and security emails are separate.",
  saved: "Preferences saved.",
  off: "Not subscribed",
  active: "Subscribed",
  pending_confirmation: "Awaiting email confirmation",
  suppressed: "Delivery paused",
  pending: "Confirm your email address before announcements begin.",
  suppressedNote:
    "Delivery is paused for this address. Contact support before subscribing again.",
  loadError: "Could not load this page. Please try again.",
  retry: "Try again",
  loading: "Loading…",
  edit: "Edit details",
  colors: "Colors",
  ivory: "Warm ivory",
  blue: "Cool blue",
  language: "Language",
  speed: "Rotation speed",
  softness: "Distance softness",
  dust: "Drifting light",
  pixel: "Pixel accents",
  fov: "View width",
  perspective: "Perspective",
  quality: "Scene detail",
  light: "Light",
  balanced: "Balanced",
  high: "High",
  reset: "Restore scene defaults",
  pause: "Pause slow rotation",
  resume: "Resume slow rotation",
  library: "Look toward the library",
  cave: "Look toward the cave",
  left: "Turn left",
  right: "Turn right",
  direction: "View direction",
  privacy: "Privacy",
  safety: "AI safety",
  updates: "Email updates",
  unsubscribe: "Unsubscribe",
  signup: "Create account",
  forgotPassword: "Reset password",
  resetPassword: "Reset password",
  verifyEmail: "Confirm email",
  accountError: "Could not complete this request. Please try again.",
};
const zh = {
  close: "关闭",
  expand: "展开",
  restore: "还原",
  sceneNavigation: "视角导航",
  environment: "图书馆与洞窟",
  home: "首页",
  about: "关于",
  news: "新闻",
  wiki: "指南",
  demo: "演示",
  get: "加入",
  login: "登录",
  settings: "设置",
  profile: "个人资料",
  yourProfile: "你的资料",
  dashboard: "控制台",
  card: "会员卡",
  pages: "网站页面",
  previous: "上一组页面",
  more: "更多页面",
  details: "详情",
  subscriptions: "订阅",
  viewCard: "查看会员卡",
  openDashboard: "打开控制台",
  finish: "完成",
  downloadCard: "下载会员卡",
  save: "保存偏好",
  newsTitle: "偶尔来信。",
  newsIntro: "选择你想收到的消息。",
  newsChoice: "Theumst 新闻",
  newsDescription: "新闻页面的新公告。",
  subscribe: "通过邮件接收 Theumst 新闻",
  optional: "可选，随时可以取消订阅。",
  footnote: "可在这里或任何公告邮件中取消订阅。账号及安全邮件单独发送。",
  saved: "偏好已保存。",
  off: "未订阅",
  active: "已订阅",
  pending_confirmation: "等待邮箱确认",
  suppressed: "邮件发送已暂停",
  pending: "确认邮箱后才会开始发送公告。",
  suppressedNote: "此邮箱的邮件发送已暂停。重新订阅前请联系支持。",
  loadError: "页面加载失败，请重试。",
  retry: "重试",
  loading: "加载中…",
  edit: "编辑详情",
  colors: "颜色",
  ivory: "暖象牙色",
  blue: "清蓝色",
  language: "语言",
  speed: "旋转速度",
  softness: "远景柔和度",
  dust: "浮光",
  pixel: "像素点缀",
  fov: "视野宽度",
  perspective: "透视",
  quality: "场景细节",
  light: "轻量",
  balanced: "均衡",
  high: "高",
  reset: "恢复场景默认设置",
  pause: "暂停缓慢旋转",
  resume: "继续缓慢旋转",
  library: "看向图书馆",
  cave: "看向洞穴",
  left: "向左转",
  right: "向右转",
  direction: "视角方向",
  privacy: "隐私",
  safety: "AI 安全",
  updates: "邮件更新",
  unsubscribe: "取消订阅",
  signup: "创建账号",
  forgotPassword: "重置密码",
  resetPassword: "重置密码",
  verifyEmail: "确认邮箱",
  accountError: "操作未完成，请重试。",
};
const ja = {
  close: "閉じる",
  expand: "拡大",
  restore: "元に戻す",
  sceneNavigation: "視点の移動",
  environment: "図書館と洞窟",
  home: "ホーム",
  about: "概要",
  news: "ニュース",
  wiki: "ガイド",
  demo: "デモ",
  get: "参加",
  login: "ログイン",
  settings: "設定",
  profile: "プロフィール",
  yourProfile: "プロフィール",
  dashboard: "ダッシュボード",
  card: "メンバーカード",
  pages: "サイトのページ",
  previous: "前のページ",
  more: "その他のページ",
  details: "詳細",
  subscriptions: "購読",
  viewCard: "カードを見る",
  openDashboard: "ダッシュボードを開く",
  finish: "完了",
  downloadCard: "カードを保存",
  save: "設定を保存",
  newsTitle: "ときどき届く便り。",
  newsIntro: "受信するお知らせを選べます。",
  newsChoice: "Theumst ニュース",
  newsDescription: "ニュースページの新しいお知らせ。",
  subscribe: "Theumst ニュースをメールで受け取る",
  optional: "任意です。いつでも購読を解除できます。",
  footnote:
    "ここから、またはお知らせメールから購読を解除できます。アカウントとセキュリティのメールは別に送信します。",
  saved: "設定を保存しました。",
  off: "未購読",
  active: "購読中",
  pending_confirmation: "メール確認待ち",
  suppressed: "配信停止中",
  pending: "メールアドレスの確認後に配信を開始します。",
  suppressedNote:
    "このアドレスへの配信は停止中です。再購読の前にサポートにご連絡ください。",
  loadError: "読み込めませんでした。もう一度お試しください。",
  retry: "再試行",
  loading: "読み込み中…",
  edit: "詳細を編集",
  colors: "色",
  ivory: "暖かなアイボリー",
  blue: "クールブルー",
  language: "言語",
  speed: "回転速度",
  softness: "遠景の柔らかさ",
  dust: "漂う光",
  pixel: "ピクセル効果",
  fov: "視野の幅",
  perspective: "遠近感",
  quality: "シーンの詳細",
  light: "軽量",
  balanced: "標準",
  high: "高",
  reset: "シーン設定を戻す",
  pause: "回転を一時停止",
  resume: "回転を再開",
  library: "図書館を見る",
  cave: "洞窟を見る",
  left: "左を向く",
  right: "右を向く",
  direction: "視線の方向",
  privacy: "プライバシー",
  safety: "AI セーフティ",
  updates: "メールで受け取る",
  unsubscribe: "購読解除",
  signup: "アカウント作成",
  forgotPassword: "パスワード再設定",
  resetPassword: "パスワード再設定",
  verifyEmail: "メール確認",
  accountError: "操作できませんでした。もう一度お試しください。",
};
export function desktopText(language) {
  return { ...en, ...({ zh, ja }[language] || {}) };
}
export function roleName(value) {
  return (
    {
      admin: "Admin",
      superadmin: "Superadmin",
      user: "User",
      betatester: "Beta tester",
      manager: "Manager",
    }[value] || "Member"
  );
}
